### ISSUE TITLE
path to file?

### ISSUE THREAD

**Issue by CleanerOrc** [InventivetalentDev/AnimatedFrames#1]
The discussion for creating a new image says you can specify a URL or a file path.  If that's accurate, is the file path relative to the plugin's AnimatedFrames folder in plugins, or to the "image" subfolder in the AnimatedFrames folder?

Would you please include examples of file path references in the command docs, or explain how the path has to be formatted to reference an image file by path?

Thanks - CO

**Comment by InventivetalentDev** [comment]
I replied to the SpigotMC thread, you need to specify the absolute file path. :)

**Comment by CleanerOrc** [comment]
Thanks!   Request to still note need full path in overview description.
