### ISSUE TITLE
AnimatedFrames Bug?

### ISSUE THREAD

**Issue by EnderCraftServer** [InventivetalentDev/AnimatedFrames#10]
## What were you expecting to happen? What happened instead?

Well the problem is: Some Users on my Spigot 1.8.8Server have bugs with the Frames, for example:
The Frame A views the USA and the Frame B Canada. So I see the Frames correctly, but my friend
see at the Frame A a piece of Frame A and Frame B. This Bugs happens quit often. But only I think 10% of my Users can see this Bug.
## What version of the plugin are you using? _Type /version &lt;Plugin Name&gt;_

Plugin: AnimatedFrames Version: 4.3.1
## What Spigot version are you using? _Type /version_

CraftBukkit version git-Spigot-db6de12-d3e0b6f (MC: 1.8.8) (Implementing API version 1.8.8-RO.1-SNAPSHOT)
## What plugins ae you using? _Type /plugins_

I am using a lot of Plugins, but no one is an plugin for frames,

OldEnchanting, PlaceholderAPI, PerWorldPlugins, Block-That-Command, PlugMan, FarmProtect, NoHitDelay, SimpleTicketManager, PartyAndFriends, Bot, BedwarsLuckyBlockAddon, VoxelSniper, MaintenanceMode, Ping, ViaVersion, Tablist, Actionbar, RealTime, CoreProtect, CustomHelpMessage, Parachute, AntiWerbung, EmptyWorldGenerator, PacketListenerApi, AdvancedBan, HealSoup, MapManager, Multiverse-Core, ProtocolLib, SimpleGrapple, NoCheatPlus, NoSpy, FastAsyncWorldEdit, Simple_PerWorldChat, AntiMinimap, DoubleJumpPlus, SuperShop, JoinFullServer, PermissionsEx, Sign_Edit, DigitalClock, ServerListPlus, Vault, UltraCosmetics, AnimatedFrames, HolographicDisplays, Chat-Formatter, MakeYourOwnCommands, TagAPI, ChestCommands, ClickWarp, WorldEdit, LeakParkour, NickNamer, Essentials, PointsAPI, 1vs1, BedwarsRel, Citizens, SchematicBrush, HeavySpleef, ChatEx, SuperVanish, PerWorldTablist, Skywars, Sentry, WorldGuard, ServerSigns, CommandNPC, WirelessRedstone, Smileychat, Lobby, SurvivalGames, Shield, JukeboxAPI
## Do you have an error log? Use [pastebin.com](http://pastebin.com). _If you're not sure, upload your whole server log_

http://pastebin.com/S709RagK
## Did your client crash? _Upload errors in .minecraft/logs/latest.log as well_

No this doesn't happened any time.
## Additional information?  _(Are you using Bungeecord? Did it work in previous versions? etc.)_

Previous versions I think before the corner update of the plugin it worked.

Sorry for my bad english >.<
EnderCraft

**Comment by InventivetalentDev** [comment]
Could you try to find an exact moment when this happens? (For example after re-joining, after a restart, after changing worlds, etc.)

**Comment by ErfinGames** [comment]
animated frames don't work on ubuntu 14.04

**Comment by InventivetalentDev** [comment]
@ErfinGames Please open a separate issue and provide more details.
