### ISSUE TITLE
Map Manager and Animated Frames wont load on PaperMC

### ISSUE THREAD

**Issue by LadyHaley** [InventivetalentDev/AnimatedFrames#107]
## What steps will reproduce the problem?  

1. Install on paperMC server
2. MM and AF dont load
3. attempt to load with plugman
4. still doesnt work

## What were you expecting to happen? What happened instead?  

The plugin to load properly

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  

AnimatedFrames_v4.11.1-SNAPSHOT
MapManager_v1.7.2-SNAPSHOT
PacketListenerAPI_v3.7.1-SNAPSHOT

## What Spigot version are you using? *Type /version*  

![2019-02-03_02-08-48](https://user-images.githubusercontent.com/3754909/52214600-1ae03080-28e6-11e9-9f2a-758f7691b8d6.png)

## What plugins are you using? *Type /plugins*  

![2019-02-03_02-08-22](https://user-images.githubusercontent.com/3754909/52214623-2a5f7980-28e6-11e9-9b4c-45b0d1bab3d8.png)

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  

https://pastebin.com/nmau76Zf

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  

No

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*

I am using PaperMC. It is a fork of Spigot, they say that there may be issues with some plugins but that they usually work to resolve it. Im using it due to the ProtocolSupport plugin

**Comment by axemwa** [comment]
It loads fine for me in Paper 522, however it breaks vanilla maps
1. Try updating to latest Paper Spigot
2. Update to latest AnimatedFrames
3. Try Removing PlugMan it's known to cause issues
