### ISSUE TITLE
AF not showing the right image

### ISSUE THREAD

**Issue by arantesxyz** [InventivetalentDev/AnimatedFrames#108]
## What steps will reproduce the problem?  
1. Just create a normal af
2. 
3. 

## What were you expecting to happen? What happened instead?  
It's showing the wrong image
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
4.11.2
## What Spigot version are you using? *Type /version*  
spigot-1.8.8 R0.1
## What plugins are you using? *Type /plugins*  
only 4, my 4 plugins and animated frames.
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
There is no error
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
there is no crash
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Its showing the wrong image, i've put 2 imagens once, and i take one of those out. Then when i create a new AF, it just always show that old image. (i'm using links, and the image is correct in my browser)

**Comment by InventivetalentDev** [comment]
Please try restarting your game and see if the correct images are shown. 
This is probably an issue with the way the image data is stored by the Minecraft client but should not affect the image that's visible over time, if you're not changing it all the time.

**Comment by arantesxyz** [comment]
Yeah. sorry, that was a minecraft related problem.
