### ISSUE TITLE
Create Issue

### ISSUE THREAD

**Issue by PapaHarni** [InventivetalentDev/AnimatedFrames#11]
## What steps will reproduce the problem?  
1. /afcreate (name) (url)

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
4.3.1

## What Spigot version are you using? *Type /version*  
1.10.2-R0.1 

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
http://pastebin.com/CBQ1MrNG

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
First time of use.

Any ideas why? Is it the SSL?

**Comment by InventivetalentDev** [comment]
This isn't really an issue with this plugin. Use another image host or make sure your SSL certificate is valid.

**Comment by PapaHarni** [comment]
It's valid. Open the image url.

**Comment by InventivetalentDev** [comment]
I did open the URL. I see that chrome sees it as valid, Java obviously doesn't. Please use another image host.
