### ISSUE TITLE
Create command not working

### ISSUE THREAD

**Issue by ChaseSantos** [InventivetalentDev/AnimatedFrames#110]
## What steps will reproduce the problem?  
Try to use a link like https://upload.wikimedia.org/wikipedia/commons/2/2c/Rotating_earth_%28large%29.gif
Also, trying to copy the full path for an image in the plugin's folder doesn't work. it just says access denied and I cannot get it to work.

## What were you expecting to happen? What happened instead?  
I expected the image to render and then place on the wall (/afcreate)

## What Spigot version are you using? *Type /version*  
![image](https://user-images.githubusercontent.com/33441571/53293126-b2bd9580-3793-11e9-8706-1557b9532d24.png)

## What plugins are you using? *Type /plugins*  
![image](https://user-images.githubusercontent.com/33441571/53293133-c23cde80-3793-11e9-8cfa-9316e29d5dff.png)

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/yp8SdGc0

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No

**Comment by InventivetalentDev** [comment]
Please try a different image.
