### ISSUE TITLE
Imaged not loading

### ISSUE THREAD

**Issue by kiritodragneel** [InventivetalentDev/AnimatedFrames#115]
## What steps will reproduce the problem?  
1.  Upload a pic to tinypic.com
2.  Create a frame using the pic url
3.  Get error log

## What were you expecting to happen? What happened instead?  
I was expecting a picture, instead got console errors and nothing happened in game to item frame, however it did send me a message saying animation competed

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
the most recent version which is 4.11.3-SNAPSHOP

## What Spigot version are you using? *Type /version*  
Version 01d0f04

## Do you have an error log?
https://pastebin.com/z0XJrTyV

**Comment by InventivetalentDev** [comment]
Make sure to update all of AnimatedFrames' dependencies.

**Comment by kiritodragneel** [comment]
All versions of the plugins and dependencies are upto date

**Comment by kiritodragneel** [comment]
https://pastebin.com/aeaQfXMb full log if it helps

**Comment by RealCorebb** [comment]
Same Problem:"java.lang.ClassNotFoundException: Could not resolve class for [ResolverQuery{name='net.minecraft.server.v1_14_R1.IntHashMap', types=[]}]"

Paper 1.14.2
Ubuntu 18
OpenJDK 1.8

**Comment by InventivetalentDev** [comment]
Please provide a list of your plugins. That part is in the issue template for a reason ;)

**Comment by InventivetalentDev** [comment]
> https://pastebin.com/aeaQfXMb full log if it helps

An actual *full log* would be quite useful, actually (so from server booting up to the error occurring)

**Comment by Th3Shadowbroker** [comment]
I reproduced the problem using Spigot 01d0f04 (1.14.2) as kiritodragneel did and I've uploaded a full log to [pastebin](https://pastebin.com/143DKH2p).

Installed plugins:
- AnimatedFrames: 4.11.3
- MapManager 1.7.3
- PacketListenerAPI 3.7.3

**Comment by InventivetalentDev** [comment]
Huh, looks like the MapManager artifact on github has some old code in it somehow. I'll try to upload the correct version.

**Comment by Th3Shadowbroker** [comment]
Jep. It's working 👍
