### ISSUE TITLE
1.9 Bug?

### ISSUE THREAD

**Issue by mclucario** [InventivetalentDev/AnimatedFrames#12]
1.  Using Spigot 1.9 git-Spigot-2038f4a-cd36f6f
2.  Starting the server
3. typing /pl

If tried to use the command which produces the picture but the plugin is just red in the plugin list.
Using plugin version 4.3.1.

Plugins:

BetterChairs.jar
BukkitSpeak.jar
CoreProtect_2.12.0.jar
craftbook-3.9-SNAPSHOT.jar
EchoPet.jar
Essentials-2.x-SNAPSHOT.jar
EssentialsChat-2.x-SNAPSHOT.jar
EssentialsGeoIP-2.x-SNAPSHOT.jar
EssentialsSpawn-2.x-SNAPSHOT.jar
FastAsyncWorldEdit-bukkit19-3.5.1-ef06ca3.jar
icJukebox-v1.6.3.jar
MineSecure.jar
MorePlayerModels_1.9.0.jar
Multiverse-Core-2.5.0-SNAPSHOT.jar
Multiverse-Portals-2.5.0-SNAPSHOT.jar
OpenInv.jar
PermissionsEx-1.23.4.jar
PluginManager-Reloaded-1.0.2.jar
SkinsRestorer.jar
TrailGUI-5.0-SNAPSHOT.jar
WayWalker.jar (small custom plugin made by me that replaces blocks on walk event)
worldedit-bukkit-6.1.2.jar
worldguard-6.1.jar

**Comment by InventivetalentDev** [comment]
Install MapManager and PacketListenerAPI, as listed in the plugin description.

**Comment by mclucario** [comment]
It would be nice if you would put it more up near the title. Just saying >.>
