### ISSUE TITLE
cant make animations

### ISSUE THREAD

**Issue by mono323** [InventivetalentDev/AnimatedFrames#126]
## What steps will reproduce the problem?  
1.  Place down Itemframes
2. Type in /framecreate name https://bit.ly/2S9lPhh
3. 

## What were you expecting to happen? What happened instead?  
it should have worked and showed me the message but it got me error see log

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
4.11.3

## What Spigot version are you using? *Type /version*  
1.13.2 paper-632

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
[latest.log](https://github.com/InventivetalentDev/AnimatedFrames/files/3374802/latest.log)
https://pastebin.com/J3bn7B7R

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
didnt crash

**Comment by InventivetalentDev** [comment]
Quite a weird error you got there. Make sure all dependencies and AnimatedFrames itself is up-to-date.  
Updating Java might help too, but I'm really not sure what's causing that error, as it technically shouldn't be possible.

**Comment by mono323** [comment]
i got it to work my bad
