### ISSUE TITLE
Huge issues with ProtocolLib

### ISSUE THREAD

**Issue by QueenAngus** [InventivetalentDev/AnimatedFrames#129]
## What steps will reproduce the problem?  
1. Getting animated frames all the dependecies
2. Attempting to create an animated frames that is animated
3. Wait until your server crashes!

## What were you expecting to happen? What happened instead?  
a frame to appear, instead it crashed

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
4.11.3-SNAPSHOT

## What Spigot version are you using? *Type /version*  
1.13.2

## What plugins are you using? *Type /plugins*  
Over 100, ProtocolLib is the one that has issues with this plugin maybe. Running protocollib 4.4.0
Could be to do with messagemute, however this plugin is custom coded.

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
Upon /aflist - https://pastebin.com/K0Jz7ZyU
Here's the error that causes the thread dump (no crash occurs) - https://pastebin.com/wLBY99tp
This only happens when trying to create a new animated frame. Non-animated works.

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Yes, and it works on some servers but not this one.

**Comment by InventivetalentDev** [comment]
Given that a NullPointer is thrown in your custom MessageMute, please check that out first.
