### ISSUE TITLE
Ubuntu 14.04.4 LTS

### ISSUE THREAD

**Issue by ErfinGames** [InventivetalentDev/AnimatedFrames#13]
## What steps will reproduce the problem?
1. 
2. 
3.

**Comment by ErfinGames** [comment]
Please help. Not working for Ubuntu 14.04.4 LTS spigot server 1.9
The plugin is not in the list

**Comment by InventivetalentDev** [comment]
Please use the provided template and answer the questions. You're still not giving me a lot of useful information.
