### ISSUE TITLE
FrameSaveEvent Async Error

### ISSUE THREAD

**Issue by realCmdData** [InventivetalentDev/AnimatedFrames#132]
## What steps will reproduce the problem?  
1.  Run the latest 1.14.4 Spigot (git-Spigot-1981d55-da62a66)
2.  /afcreate https://media3.giphy.com/media/Qm2hcQIpSM9cQ/giphy.gif
3.  Item Frame canvas of 4 high by 5 wide
4.  Follow plugin instructions

## What were you expecting to happen? What happened instead?  
Expected for the gif to render properly. Caused an unhandled exception.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
4.11.3-SNAPSHOT

## What Spigot version are you using? *Type /version*  
1.14.4

## What plugins are you using? *Type /plugins*  
https://i.imgur.com/QvPbog0.png

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/LD8jtNjb

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No

**Comment by InventivetalentDev** [comment]
Duplicated of #131
