### ISSUE TITLE
Itemsframe not generating? 

### ISSUE THREAD

**Issue by Danielh101** [InventivetalentDev/AnimatedFrames#134]
## What steps will reproduce the problem?  
1. /afcreate {name} link
2. Click the area of the itemframes
3. Look in too console

## What were you expecting to happen? What happened instead?  
Picture to show up

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
https://i.imgur.com/peTf25p.png
## What Spigot version are you using? *Type /version*  
https://i.imgur.com/kZNRwuR.png

## What plugins are you using? *Type /plugins*  
(Private message me and I'll show) 

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://i.imgur.com/XFnDENe.png
https://i.imgur.com/8ldElXa.png

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
No

**Comment by LoganTheOverlord** [comment]
Same error for me (PaperSpigot 1.14.4)

**Comment by InventivetalentDev** [comment]
Please try if an older version (not yet updated to 1.14) of AF fixes the issue
