### ISSUE TITLE
Problems with the images

### ISSUE THREAD

**Issue by TheModz01** [InventivetalentDev/AnimatedFrames#135]
## What steps will reproduce the problem?  
1. /afcreate Name Link
2. /restart
3. Go to another world with AnimatedFrames

## What were you expecting to happen? What happened instead?  

I hoped that when the images were ripped they would look correctly

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  

![0f8fa8adeab08e123276a95bf5f12f1b](https://user-images.githubusercontent.com/28708984/64831315-776ea100-d5d5-11e9-8afb-c89d66ec1d4d.png)

## What Spigot version are you using? *Type /version*  

![6701a594e8b6dfcbf84c62cea37cd448](https://user-images.githubusercontent.com/28708984/64831297-645bd100-d5d5-11e9-98d9-ebea6cf27b05.png)

## What plugins are you using? *Type /plugins*  

![d5b18201ab26e06dbb1c676d39162f93](https://user-images.githubusercontent.com/28708984/64831291-5f971d00-d5d5-11e9-870b-9142608e2738.png)

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  

No

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  

No

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*

![2019-09-13_03 13 26](https://user-images.githubusercontent.com/28708984/64831281-573ee200-d5d5-11e9-844b-2825dc32d248.png)
![2019-09-13_03 14 07](https://user-images.githubusercontent.com/28708984/64831282-573ee200-d5d5-11e9-8938-5ee48fba3de1.png)
![2019-09-13_03 14 10](https://user-images.githubusercontent.com/28708984/64831283-57d77880-d5d5-11e9-887d-61c255c6257d.png)

**Comment by InventivetalentDev** [comment]
Does restarting your client fix it?

**Comment by TheModz01** [comment]
No, and it doesn't just happen to me, it's the whole server...

**Comment by InventivetalentDev** [comment]
Is this happening to all images or just the ones you screenshotted?   
Do the images look correct when first creating them?  
Which direction are the frames facing (look directly at the images and check `Facing` in the F3 overlay)?

**Comment by TheModz01** [comment]
It happens to all images when I change from one world to another, and the images are in all directions...

And when they are created they look good until you change the world.

**Comment by InventivetalentDev** [comment]
Appears to be an issue with the 1.8.8 client.  
I can't reproduce it in newer MC versions and 1.8 support isn't really a priority.

**Comment by TheModz01** [comment]
Should i user 1.12 minecraft server?

**Comment by InventivetalentDev** [comment]
if you would like this plugin to function properly, yes.
