### ISSUE TITLE
Problem with AnimatedFrames

### ISSUE THREAD

**Issue by xXRedMercyXx** [InventivetalentDev/AnimatedFrames#141]
Everything working perfect! But when it starts to load a gif it cannot load.Im running Spigot 1.10 and latest version of this plugin with packetlistenerapi and mapmanager of course  (sorry for my bad english)
Thats the console message :
[INFO] [AnimatedFrames] Generating image data for test1...

[INFO] [AnimatedFrames] Downloaded 'https://media.giphy.com/media/l0HlN5tqr0QQQbWvK/giphy.gif' to 'plugins/AnimatedFrames/images/aHR0cHM6Ly9tZWRpYS5naXBoeS5jb20vbWVkaWEvbDBIbE41dHFyMFFRUWJXdksvZ2lwaHkuZ2lm'.

[INFO] [AnimatedFrames] Animation length for 'test1' is zero. Creating non-animated image.

[WARNING] Exception in thread "pool-19-thread-5"

[WARNING] java.lang.RuntimeException: Failed to read the given image. Please make sure you're using a valid source

[WARNING] at org.inventivetalent.animatedframes.AnimatedFrame.run(AnimatedFrame.java:152)

[WARNING] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

[WARNING] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

[WARNING] at java.lang.Thread.run(Thread.java:813)

**Comment by xXRedMercyXx** [comment]
so can i fix it ? :D

**Comment by InventivetalentDev** [comment]
Try another image url. If the issue keeps persisting, please use the issue template when opening another one.
