### ISSUE TITLE
ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by Dymeth** [InventivetalentDev/AnimatedFrames#145]
The problem occurs 3 seconds after the server starts.
The problem started a long time ago, so I can’t say whether it is related to a specific version of the plugin.
I think the problem arose due to the use of an incorrect image.
In any case, it would be nice to display the name of the frame / file with which the problem

**Plugin version:**
AnimatedFrames version 4.11.3-SNAPSHOT

**Spigot version:**
This server is running Paper version git-Paper-652 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Installed plugins:**
AnimatedFrames*, BKCommonLib, MapManager*, PacketListenerApi*, ProtocolLib*, ProtocolSupport, ViaVersion* (and some others)

**Error log:**
https://pastebin.com/raw/YjE7g2Gs

**Comment by InventivetalentDev** [comment]
Since `Gondor` is started immediately before that error, I'm gonna take a guess and say that's the faulty image. Try removing that - you can also delete the file in the plugin directory.

**Comment by Dymeth** [comment]
https://pastebin.com/raw/PgU3Yhey


> Since `Gondor` is started immediately before that error, I'm gonna take a guess and say that's the faulty image. Try removing that - you can also delete the file in the plugin directory.

In fact, the error does not occur immediately after loading a particular image. For example, it arose after loading Star: https://pastebin.com/raw/PgU3Yhey
In general, it’s not a problem to find a problem image, but it will be easier if a specific name is still displayed when exceptions occur

**Comment by InventivetalentDev** [comment]
Hmm, I see. I'll look into adding more information to any errors that occur.

**Comment by Dymeth** [comment]
Ok, now I managed to find the link where the problem image was downloaded:
https://en.wikipedia.org/wiki/Gondor#/media/File:Escudo_Gondor.svg
It might be worth adding a little validation when trying to add a picture.
