### ISSUE TITLE
Adding AnimatedFrames over Position X Zero

### ISSUE THREAD

**Issue by Bl4ckSkull666** [InventivetalentDev/AnimatedFrames#147]
## What steps will reproduce the problem?  
1. Place Frames from  x:-1 to x:1 
2. Add Gif that's (WxH) 96x32 pixel.
3. Only frame on X 0 will be filled and animated.
( [Video Youtube](https://www.youtube.com/watch?v=GoM5jGk33u0) )

1. Place frames from x:1 to x:-1
2. Add Gif that's (WxH) 96x32 pixel.
3. Only frames on x 0 and x 1 are filled and animated. 

## What were you expecting to happen? What happened instead?  
3. Only frame on X 0 will be filled and animated. ( What steps will reproduce the problem? )
3. Only frames on x 0 and x 1 are filled and animated. ( What steps will reproduce the problem? )

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
4.11.4 AnimatedFrames
1.7.4 MapManager
3.7.5 PacketListenerAPI

## What Spigot version are you using? *Type /version*  
Paper v235 ( Mc v. 1.14.4 )

## What plugins are you using? *Type /plugins*  
few

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
No Error

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No Error

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
I don't know.

**Comment by InventivetalentDev** [comment]
Appears to be an issue with the placement logic (/afc), since displaying frames over x=0 seems to work fine.

**Comment by Bl4ckSkull666** [comment]
But look the Video, you see that's not load. Same issue with updated Plugin and Server.  Restart don't fix it too.
