### ISSUE TITLE
Problem with /afcreate

### ISSUE THREAD

**Issue by MagnusTv** [InventivetalentDev/AnimatedFrames#148]
## What steps will reproduce the problem?  
1. /afcreate KM1 https://repo.reydio.eu/images/fresselachs/SkyBlocks/Kohlemine.jpg
2. Error in Console: https://i.imgur.com/WEm49uu.png

## What were you expecting to happen? What happened instead?  
Creating an Image/Frame
Nothing + Error in Console (https://i.imgur.com/WEm49uu.png)

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
https://i.imgur.com/JnVeUyM.png

## What Spigot version are you using? *Type /version*  
https://i.imgur.com/0eGwwby.png

## What plugins are you using? *Type /plugins*  
https://i.imgur.com/e6NsXhw.png

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/W1FiSL2p

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
No

**Comment by InventivetalentDev** [comment]
A quick google search for the error lead me to https://stackoverflow.com/questions/10165761/java-cant-connect-to-x11-window-server-using-localhost10-0-as-the-value-of-t

Try
> export DISPLAY=:0    
(https://stackoverflow.com/a/15068584/6257838)  

and/or 

> specify the -Djava.awt.headless=true parameter at startup time    
(https://stackoverflow.com/a/10165905/6257838)

**Comment by MagnusTv** [comment]
Thank you it works 😄
