### ISSUE TITLE
GIFs don't work. Tried several ones

### ISSUE THREAD

**Issue by derMiepz** [InventivetalentDev/AnimatedFrames#149]
## What steps will reproduce the problem?  
1. Search for a GIF
2. Try to create a frame with /afcreate NAME LINK
3. Check your console. This is all you get ingame ![](https://i.imgur.com/aSWKmti.png)

## What were you expecting to happen? What happened instead?  
It should create a frame but it got stuck.
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
AnimatedFrames_v4.11.4-SNAPSHOT.jar
## What Spigot version are you using? *Type /version*  
```
[13:35:27] [Server thread/INFO]: --------------------------------------------------
[13:35:27] [Server thread/INFO]: CMI Plugin Version: 8.6.16.5 BungeeCord 
[13:35:27] [Server thread/INFO]: Server Version: Spigot 1.15.1-R0.1-SNAPSHOT
[13:35:27] [Server thread/INFO]: Vault Version: 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
[13:35:27] [Server thread/INFO]: --------------------------------------------------
```
## What plugins are you using? *Type /plugins*  
CoreProtect, LuckPerms, WorldEdit, PlaceholderAPI, Lift, PacketListenerApi, PlugMan, Lands, MapManager, Multiverse-Core, ProtocolLib, WorldGuard, IPAUtils, Multiverse-Portals, Vault, TokenManager, BungeeTeleport, dynmap, AnimatedFrames, WorldBorder, HeadDatabase, QuickShop, Citizens, MysqlPlayerDataBridge, PremiumVanish, BeautyQuests, CMI, CitizensCMD, BungeeTabListPlus
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
Errors with different images: https://pastebin.com/EeENNpae - https://pastebin.com/RehJ6vH5

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
We're using BungeeCord. Images work just fine, GIFs don't. Haven't tried other versions. First time using the plugin. 
GIFs I was having problems with: 
https://media.giphy.com/media/lnakK4SbSca7MHf5Ti/giphy.gif (version I uploaded to imgur: https://i.imgur.com/n7avHIJ.gifv)
https://media.giphy.com/media/139eZBmH1HTyRa/source.gif

**Comment by InventivetalentDev** [comment]
The one from imgur is a `gifv` and the giphy one returns a html page and not the image when using the `media` subdomain.  

https://i.imgur.com/n7avHIJ.gif and https://i.giphy.com/media/139eZBmH1HTyRa/giphy.gif should work.

**Comment by derMiepz** [comment]
How did you get the `i.giphy.com` version? The "zombie riding" was just for testing. I only get the media subdomains, even when right clicking the image > open in new tab ![](https://i.imgur.com/uXpXY7G.png)

**Comment by InventivetalentDev** [comment]
Just manually change it ^^ (replace media with i)

**Comment by derMiepz** [comment]
Oh wow :D It thought that this'd be waaay more complicated. Thanks for your help and fast responses! <3
