### ISSUE TITLE
New Maps geting Frames from AnimatedFrames

### ISSUE THREAD

**Issue by SoraCent** [InventivetalentDev/AnimatedFrames#154]
## What steps will reproduce the problem?  
1. Create a Map
2. Using the Map

## What were you expecting to happen? What happened instead?  
It should create a normal Map of the World but Gets a Frame of a Picture / Gif from AnimatedFrames
Edit: Same with Treasure and Structure Maps

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
4.11.4-SNAPSHOT

## What Spigot version are you using? *Type /version*  
Paper-77 for 1.15.2

## What plugins are you using? *Type /plugins*  
MapManager 1.7.7, PacketListenerAPI 3.7.5

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  

26.01 22:37:51 [Server] INFO [MapManager] Adding new Map #156 to occupied IDs.

**Comment by InventivetalentDev** [comment]
See https://github.com/InventivetalentDev/AnimatedFrames/issues/106
