### ISSUE TITLE
Failed to read given image

### ISSUE THREAD

**Issue by Exorsin** [InventivetalentDev/AnimatedFrames#155]
## What steps will reproduce the problem?  
1. /afcreate water https://media.giphy.com/media/fTyA1LpcOhTEustaEV/giphy.gif
2. 
3. 

## What were you expecting to happen? What happened instead? 
 
Image did not load
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*
  
AnimatedFrames version 4.11.4-SNAPSHOT

## What Spigot version are you using? *Type /version* 
 
Craftbukkit version:
git-Spigot-56f8471-6567017 (MC: 1.14.4) (Implementing API version 1.14.4-R0,1-SNAPSHOT)

## What plugins are you using? *Type /plugins*
  
luckperms, worldedit, worldeditSUI, placeholderAPI, packetlistnerAPI, clearlag, mapmanager, multiverse-core, protocollib, worldguard, nocheatplus, partyandfriends,images,minepacks,voidgenerator,conditionalcommands,projectkorra,vault,
venturechat,bendingessentials,advancedregionmarket,essentials,animatedframes,jobs,bendinggui,commandssigns,essentialsxmpp,discordsrv,essentialsprotect,projectaddons,essentialsgeoip,essentialsantibuild,essentialsspawn

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*
  
27.01 04:41:38 [Server] Server thread/INFO exorsin issued server command: /afcreate water https://media.giphy.com/media/fTyA1LpcOhTEustaEV/giphy.gif
27.01 04:41:42 [Server] pool-48-thread-12/INFO Generating image data for water...
27.01 04:41:42 [Server] pool-48-thread-12/INFO Downloaded 'https://media.giphy.com/media/fTyA1LpcOhTEustaEV/giphy.gif' to 'plugins/AnimatedFrames/images/aHR0cHM6Ly9tZWRpYS5naXBoeS5jb20vbWVkaWEvZlR5QTFMcGNPaFRFdXN0YUVWL2dpcGh5LmdpZg=='.
27.01 04:41:42 [Server] pool-48-thread-12/INFO Animation length for 'water' is zero. Creating non-animated image.
27.01 04:41:42 [Server] pool-48-thread-12/WARN Exception in thread "pool-48-thread-12" 
27.01 04:41:42 [Server] pool-48-thread-12/WARN java.lang.RuntimeException: Unexpected exception in AnimatedFrame water
27.01 04:41:42 [Server] pool-48-thread-12/WARN at org.inventivetalent.animatedframes.AnimatedFrame.run(AnimatedFrame.java:286)
27.01 04:41:42 [Server] pool-48-thread-12/WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
27.01 04:41:42 [Server] pool-48-thread-12/WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
27.01 04:41:42 [Server] pool-48-thread-12/WARN at java.lang.Thread.run(Thread.java:748)
27.01 04:41:42 [Server] pool-48-thread-12/WARN Caused by: java.lang.RuntimeException: Failed to read the given image. Please make sure you're using a valid source
27.01 04:41:42 [Server] pool-48-thread-12/WARN at org.inventivetalent.animatedframes.AnimatedFrame.run(AnimatedFrame.java:153)
27.01 04:41:42 [Server] pool-48-thread-12/WARN ... 3 more

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
no

**Comment by Exorsin** [comment]
I also tried the various different links that GIPHY provides, but to no avail.  None of them worked.

**Comment by InventivetalentDev** [comment]
i.giphy.com

**Comment by chipcoint** [comment]
> i.giphy.com

you should say that in a tutorial or smth because until i found that post here i could not get a single gif to work (if you said it or wrote it somewhere i guess i am blind xD)

**Comment by InventivetalentDev** [comment]
added it to the plugin page c:
