### ISSUE TITLE
Game crashes on certain gifs

### ISSUE THREAD

**Issue by Lerfing** [InventivetalentDev/AnimatedFrames#156]
## What steps will reproduce the problem?  
1. Use this gif https://thumbs.gfycat.com/ThoroughRecklessBlacknorwegianelkhound-size_restricted.gif (I suspect that this is because of its image size, which is 333 x 250)
2. I used on a 3x5 item frames
3. GIF will take a while to load, look weird, then crash players near the end of it. When logging back in image will take about 2 minutes to load then crash your game the moment it loads

## What were you expecting to happen? What happened instead?  
Game crashes
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
AnimatedFrames_v4.11.4-SNAPSHOT
## What Spigot version are you using? *Type /version*  
1.12.2 final
## What plugins are you using? *Type /plugins*  
CustomFishing, PlaceholderAPI, ConsoleSpamFix, AdvancedHelp, VoxelSniper, EpicWorldGenerator, CraftingStore, AsyncWorldEditInjector, CratesPlus, EpicNetherGenerator, LuckPerms, PacketListenerApi, MessageAnnouncer, MapManager, Votifier, McTeams, Multiverse-Core, MCCore, AdvancedPortals, VotingPlugin, AsyncWorldEdit, CS-CoreLib, Multiverse-Portals, AntiBotAttack, Vault, ColoredAnvils, Lores, TreysDoubleJump, AnimatedFrames, KillerMoney, SignShop, Holograms, Images, ViaVersion, WorldEdit, Denizen, Essentials, ProtocolLib, LibsDisguises, EssentialsChat, SuperbVote, ServerListPlus, WorldGuard, EssentialsXMPP, ChatItem, MythicMobs, Slimefun, Duels, AddLight, EssentialsSpawn, CustomEnchantments, MythicMobsExtension, AreaShop, CustomEnderChest, Jobs, MMOItems, Shopkeepers, KeepChunks, GriefPrevention, MoarBows, Parties
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
No errors
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
yes https://pastebin.com/Xq1puRTs
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
replicated this on two different servers with different plugins, also love your plugins :)

**Comment by InventivetalentDev** [comment]
Is that your whole client crash log? Since I can't see any specific errors

**Comment by Lerfing** [comment]
Yes

**Comment by InventivetalentDev** [comment]
So I tried it myself with the same image & version but didn't crash. So not sure why this is happening for you.  https://www.youtube.com/watch?v=2DZQbo-PiII

**Comment by InventivetalentDev** [comment]
![](https://yeleha.co/2th2ind)

**Comment by InventivetalentDev** [comment]
I was able to reproduce at least a decrease in game performance (leading to frame drops) when placing a lot of frames in one spot.  

So this is most likely an issue with the client running out of memory to store all the image data, which I can't do much about other than advise using shorter/smaller animations.
