### ISSUE TITLE
Getting a NullPointerException that kicks players when removing frames

### ISSUE THREAD

**Issue by derMiepz** [InventivetalentDev/AnimatedFrames#157]
## What steps will reproduce the problem?  
1. Use `/afcreate` to create a frame (Example: `/afcreate testemote https://i.imgur.com/GPILyHx.png`)
2. Remove it with `/afremove`
3. Check your ingame chat and console for the error

## What were you expecting to happen? What happened instead?  
Remove the frame without kicking the players. Frame got removed, players got kicked.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
`AnimatedFrames_v4.11.4-SNAPSHOT.jar`
## What Spigot version are you using? *Type /version*  
`
Server Version: Spigot 1.15.2-R0.1-SNAPSHOT
`
## What plugins are you using? *Type /plugins*  
`Plugins (38): CoreProtect, LuckPerms, WorldEdit, PlaceholderAPI, Lift, PacketListenerApi, PlugMan, Lands, MapManager, Multiverse-Core, ProtocolLib, WorldGuard, IPAUtils, React, Multiverse-Portals, Vault, TokenManager, BungeeTeleport, dynmap, AdvancedRegionMarket, AnimatedFrames, WorldBorder, HeadDatabase, HolographicDisplays, Citizens, FurnitureLib, FurnitureMaker, Backpacks, DiceFurniture, PremiumVanish, BeautyQuests, CMI, CitizensCMD, BungeeTabListPlus, MyPet, QuickShop, ArmQuickShopBridge, MysqlPlayerDataBridge
`
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/bZeQdyfv
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
We're using BungeeCord. Issue started to appear out of nowhere. Was working fine for weeks.

**Comment by InventivetalentDev** [comment]
Please set debug=true in server.properties so the errors are a bit more detailed and try to reproduce the issue.

**Comment by derMiepz** [comment]
I might've fixed the issue already by updating MapManager from 1.7.6-SNAPSHOT to 1.7.7-SNAPSHOT. The problem didn't occur again after updating it, but I wouldn't close this issue for now so I can do some more testing and get back to you later today / tomorrow, just to make sure this was the actual root of the problem. ^^

**Comment by derMiepz** [comment]
Okay so I think everything is back to normal now. Did some more testing and couldn't replicate it. :D
