### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Bodyash** [InventivetalentDev/AnimatedFrames#16]
http://pastebin.com/Bh5UyYup After AF update and few hours of runtime

**Comment by InventivetalentDev** [comment]
Did you change anything else? I'm currently not sure how the changes I made could crash a server.

**Comment by Bodyash** [comment]
Fast Async World Edit, https://github.com/boy0001/FastAsyncWorldedit, but NOONE has a permission to use it, only me. I will test more, and say, if crash happens again.
