### ISSUE TITLE
The plugin will not load in and are red in /pl!

### ISSUE THREAD

**Issue by vinziiiz** [InventivetalentDev/AnimatedFrames#161]
## What steps will reproduce the problem?  
1.  Red marked in plugin list when i check with /pl
2. The plugin will not load in...

## What plugins are you using? *Type /plugins*  
Plugins (30): LuckPerms, WorldEdit, PlaceholderAPI, ClearLag, AnimatedFrames, HolographicDisplays, LuckPermsGUI, Votifier, WorldGuard, Multiverse-Core, AdvancedPortals, NetherPortal, Janky, WitherAC, Vault, CoreProtect, ChestShop, Essentials, Towny, Jobs, VotingPlugin, EssentialsProtect, EssentialsGeoIP, EssentialsChat, Parkour, TAB, HungerGames, EssentialsSpawn, SpleefX, Harbor

**Comment by InventivetalentDev** [comment]
https://github.com/InventivetalentDev/AnimatedFrames/issues/162#issuecomment-599697489
