### ISSUE TITLE
Red marked in plugin list!

### ISSUE THREAD

**Issue by vinziiiz** [InventivetalentDev/AnimatedFrames#162]
## What steps will reproduce the problem?  
1.  Red marked in plugin list when i check with /pl
2. The plugin will not load in...

## What were you expecting to happen? What happened instead?  Naffing happend, i trying to install the plugin only. 

##Version spigot:
AnimatedFrames version 4.11.4-SNAPSHOT 

## What plugins are you using? *Type /plugins*  
Plugins (30): LuckPerms, WorldEdit, PlaceholderAPI, ClearLag, AnimatedFrames, HolographicDisplays, LuckPermsGUI, Votifier, WorldGuard, Multiverse-Core, AdvancedPortals, NetherPortal, Janky, WitherAC, Vault, CoreProtect, ChestShop, Essentials, Towny, Jobs, VotingPlugin, EssentialsProtect, EssentialsGeoIP, EssentialsChat, Parkour, TAB, HungerGames, EssentialsSpawn, SpleefX, Harbor

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)* 
No Bungeecord

**Comment by InventivetalentDev** [comment]
install the dependencies.
