### ISSUE TITLE
server file not not generating

### ISSUE THREAD

**Issue by coolkidmacho** [InventivetalentDev/AnimatedFrames#163]
## What steps will reproduce the problem?  
1. The file does not load
2. it is red in chat when i do /pl

## What were you expecting to happen? What happened instead?  
there to be a file to put my gifs in
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
latest - 4.11.3 snapshot
## What Spigot version are you using? *Type /version*  
1.15.2
## What plugins are you using? *Type /plugins*  
Only this one
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
There are no errors
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
no
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
no

**Comment by InventivetalentDev** [comment]
Install the dependencies.
