### ISSUE TITLE
Images quit displaying randomly

### ISSUE THREAD

**Issue by OverDhill** [InventivetalentDev/AnimatedFrames#164]
## What steps will reproduce the problem?  
1. Random
![bug](https://user-images.githubusercontent.com/16721700/78026933-73fcf600-732a-11ea-96ab-72771dac9d17.jpg)

2. 
3.

**Comment by zettlinger** [comment]
Same Issue as OverDhill, worked then stopped without any interaction

**Comment by OverDhill** [comment]
> 
> 
> Same Issue as OverDhill, worked then stopped without any interaction .14 snapshot .15 didnt restart it

The sad part is he won't even respond to this problem even though I posted on it a few times in his discussion section for this plugin.
