### ISSUE TITLE
GIF isnt visible after going out of renderdistance

### ISSUE THREAD

**Issue by chipcoint** [InventivetalentDev/AnimatedFrames#166]
## What steps will reproduce the problem?  
1.  Make a working GIf 
2.  Go away (out of render distance (i think))
3.  go back

## What were you expecting to happen? What happened instead?  
Expected: see the gif i placed there.
Happened:  Gif is not visible any more.
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
4.11.5-SNAPSHOT
## What Spigot version are you using? *Type /version*  
Spigot 1.15.2-R0.1-SNAPSHOT
## What plugins are you using? *Type /plugins*  
WebAdmin, Vault, ServerRestorer, BlockLocker, PacketListenerApi, TimeIsMoney, ShopChest, XConomy, MapManager,AnimatedFrames
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
There is no error because the gifs still work they are just not visible any more
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
 No
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
i dont think so xD

**Comment by InventivetalentDev** [comment]
the images should refresh automatically after a couple of seconds

**Comment by chipcoint** [comment]
Okay so i just rejoined the server (first time since i uploaded the issue ) and the frames that were in my render range are now loaded and play and visible (also when i go away and come back) but every other gif is not loading any more. (there is nothing in the log and is there a command to reload the frames?) i have currently set the gifs to not start automatically and now i started the other gifs which didnt load (i assume because i didnt start them) but i dont see them still

**Comment by chipcoint** [comment]
Update (i was not online for an hour and now rejoined) and now all the gifs are loading
