### ISSUE TITLE
AnimatedFrames issue

### ISSUE THREAD

**Issue by Lukajjza** [InventivetalentDev/AnimatedFrames#17]
## What steps will reproduce the problem?
1. /afplace
2. Right click bottom left corner
3. Right click upper right corner
## What were you expecting to happen? What happened instead?

Place item frames. It said frames placed, but nothing happened.
## What version of the plugin are you using? _Type /version &lt;Plugin Name&gt;_

4.3.2
## What Spigot version are you using? _Type /version_

1.10.2-R0.1-SNAPSHOT
## What plugins are you using? _Type /plugins_

Bookshelves, SkinsRestorer, WorldEdit, PacketListenerApi, PermissionsEx, PluginManagerReloaded, VerticalRails, OneWayBlocks, AdvancedSlabs, MapManager, Vault, InventoryScroll, Multiverse-core, ProtocolLib, Essentials, ProtectionLib, MapMenus, FurnitureLib, DiceFurniture and of course AnimatedFrames
## Do you have an error log? Use [pastebin.com](http://pastebin.com). _If you're not sure, upload your whole server log_

Console "says" nothing. Last thing there is: ... issued server command: /afplace
## Did your client crash? _Upload errors in .minecraft/logs/latest.log as well_

no

**Comment by InventivetalentDev** [comment]
What type of block are you trying to place the frames on?  
I'm pretty sure this is caused by another plugin preventing the frames from spawning. Please try to place the same frames on a separate server with only AnimatedFrames and the dependencies installed.
