### ISSUE TITLE
Frame not appearing for player after re-logging

### ISSUE THREAD

**Issue by halofreak894** [InventivetalentDev/AnimatedFrames#178]
## What steps will reproduce the problem?  
1. Create an animatedframe using the plugin in any spot
2. Leave the server
3. Come back to that spot

## What were you expecting to happen? What happened instead?  
I was expecting for the frame to just start playing again for that player, but instead, it just doesn't appear.
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
4.11.5
## What Spigot version are you using? *Type /version*  
1.12.2
## What plugins are you using? *Type /plugins*  
AnimatedFrames, Animatronics, ArmorStandEditor, ArmorStandTools, BKCommonLib, CoreProtect, MapManager, ModelMaker, PacketListenerApi, ProtocolLib, ProtocolSupport, TCCoasters, Train_Carts, ViaVersion, WorldEdit, WorldEditSelectionVisualizer, WorldGuard. All other plugins are custom-made. If you need those listed I can do so.
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
N/A
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
N/A
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Yes, Bungeecord is being used. Not sure about working in previous versions.

**Comment by TheNety** [comment]
Yep sometimes the frames are just empty and it never loads... Using Paper 1.15.2

**Comment by Dimatron74** [comment]
Yes, this is constantly. The bug is really significant, the developer should deal with it. Paper 1.12.2
