### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by theismarius** [InventivetalentDev/AnimatedFrames#18]
## What steps will reproduce the problem?
1.  when i select to the corners to paste the image the image after doesnt appear
2. 
3. 
## What were you expecting to happen? What happened instead?

to see an image, and didnt show up
## What version of the plugin are you using? _Type /version &lt;Plugin Name&gt;_

no 4.3.2 but also didnt work in 4.3.0
## What Spigot version are you using? _Type /version_

doesnt show up but 1.9 mc version
## What plugins are you using? _Type /plugins_

block particles
lift
head items
lasers
realisticgrave
spanwjoin
fancyportals
spawner
lockette
pixelator
transport pipes
magical weapons
morebows
lightapi
crates plus
dynmap
frameprotect
worldedit
alchemical arrows
cityworld
essentials
headleaderboards
packetlistenerapi
clearlag
throwdisks
advancedarrowtrail
banrecipe
crackshot
jukeloop
mapmanager
multiverse core
protocollib
autosaveworld
kitadder
betterproxyjoin
swiftcore
essentialspinplease
permissionex
placeable bread
lottery
toaster
boots
mineresetlit
vault
coloredanvils
skinsrestorer
punishmental
furniturelib
bows plus
stafflist
customenchantments
wireless redstone
mcjobs
towny
warpportals
townychat
magicalmoneydrop
cs-corelib
dicefurniture
chestshop
mychunk
slimefun
quickmarket
slimefun  luckyblocks
exotic gardens
gun fun
magicloot
colored enderchests
## Did your client crash? _Upload errors in .minecraft/logs/latest.log as well_

no
## Additional information?  _(Are you using Bungeecord? Did it work in previous versions? etc.)_

im using bungeecord and didnt work on previous verssions

**Comment by InventivetalentDev** [comment]
Please post a link to the image you tried to use. 
Do you get any error/confirmation messages in chat? (e.g. 'First corner set', 'Second corner set', 'Animation started')

**Comment by InventivetalentDev** [comment]
An exact server version would also be helpful, run /version in the console if you don't have permissions to do it ingame.

**Comment by theismarius** [comment]
1.9 spigot alpha by the way i found it was the magic plugin so i used a downgraded version of animated frames, to 3.x how can i make an image as the soze i want in 3.x version?

**Comment by InventivetalentDev** [comment]
There is no '1.9 spigot alpha' version. Run /version and post the output.
