### ISSUE TITLE
Error in see frames // error console

### ISSUE THREAD

**Issue by willypro7** [InventivetalentDev/AnimatedFrames#182]
## What steps will reproduce the problem?  
1.   /afcreate tv3 https://i.ibb.co/Z2wRxLJ/image.png
2.   Err in console
3.   Nothing 

## What were you expecting to happen? What happened instead?  

Creating a image //  getting an error, and don't see any image

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  

Lastest

## What Spigot version are you using? *Type /version*  

![image](https://user-images.githubusercontent.com/66904521/92505895-eee50980-f204-11ea-94dd-3e62d35ba9e4.png)

## What plugins are you using? *Type /plugins*  

![image](https://user-images.githubusercontent.com/66904521/92505850-d8d74900-f204-11ea-81e1-d8ed6cb15bea.png)

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  

https://pastebin.com/dq75Y4aK

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  

No

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*

No, is a singre server

**Comment by willypro7** [comment]
nO no close or gay

**Comment by willypro7** [comment]
Still need help

**Comment by InventivetalentDev** [comment]
Did you updated your plugins in the meantime? I've released a couple new versions since you created this issue.
