### ISSUE TITLE
AnimatedFrames plugin not enabling correctly

### ISSUE THREAD

**Issue by LastHop3** [InventivetalentDev/AnimatedFrames#19]
## What steps will reproduce the problem?  
1.  I start up the server.
2.  I do nothing else.
3.  And an error shows up while enabling the plugin.

## What were you expecting to happen? What happened instead?  
To see no errors on startup.
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
AnimatedFrames v4.3.2 | PacketListenerAPI v3.4.4 | MapManager v1.2.0
## What Spigot version are you using? *Type /version*  
I'm using CraftBukkit version git-Bukkit-7f9fbe5 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
## What plugins are you using? *Type /plugins*  
There are no other plugins besides the three mentioned.
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
http://pastebin.com/mHQh89ji
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
Client does not crash.
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
I tried AnimatedFrames v4.3.1 and it still produced the same error

**Comment by InventivetalentDev** [comment]
Use Spigot, please. CraftBukkit won't work properly for most of my plugins.
