### ISSUE TITLE
Empty tiles

### ISSUE THREAD

**Issue by TheNety** [InventivetalentDev/AnimatedFrames#191]
## What steps will reproduce the problem?  
1. Create image
2. Let the time flow, rejoin server or go to another world
3. Look at the image

## What were you expecting to happen? What happened instead?  
I expected to see the image. Instead it's just empty tiles. It happens very often. Server restart is needed to actually see the image. This issue is here for really long time, we would really appreciate if you could try to fix it. It has been also reported in this issue https://github.com/InventivetalentDev/AnimatedFrames/issues/178 and maybe much more.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
4.12.1-SNAPSHOT

## What Spigot version are you using? *Type /version*  
Paper 1.16.4

**Comment by Killma** [comment]
same error for me

**Comment by TheNety** [comment]
still relevant
