### ISSUE TITLE
Plugin not starting when using "new" Java versions (>=12)

### ISSUE THREAD

**Issue by Fabb111** [InventivetalentDev/AnimatedFrames#196]
## What steps will reproduce the problem?  
1. Use Java >=12
2. Start the server

## What were you expecting to happen? What happened instead?  

I expected the plugin to enable without problems, instead it throws an exception.
See: https://gist.github.com/Fabb111/e8e96aa38efc21799e1d24af2bec8732

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  

Latest (4.12.1-SNAPSHOT)

## What Spigot version are you using? *Type /version*  

Paper Spigot 1.16.4

## What plugins are you using? *Type /plugins*  

None (except required ones)

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  

https://gist.github.com/Fabb111/e8e96aa38efc21799e1d24af2bec8732

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  

\-

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*

https://github.com/InventivetalentDev/PluginAnnotations/blob/02b6e7e85bf7c4f7ef2d0e371c218d0993369fb0/src/main/java/org/inventivetalent/pluginannotations/AccessUtil.java#L15
is causing the problem; As it seems like you already fixed it in master, the solution would probably be releasing the new version of PluginAnnotations and updating the dependency here

**Comment by TombPlays** [comment]
I can second this error on 1.16.5. I;m on Java 15 as advised to update to 11 or higher by the server as in 1.17 lower versions won't be supported. Will try downgrading to 11

**Comment by TombPlays** [comment]
I can confirm that downgrading to Java 11 fixed this for me. Strange as java is suppose to be backwards compatible
