### ISSUE TITLE
I cannot generate the frames

### ISSUE THREAD

**Issue by DenDerErn** [InventivetalentDev/AnimatedFrames#2]
When i try, to make a gif ingame, it just says Loading Image & Generating File... and Saving frame data to file.. and Starting playback, and it stops there.

i have this error in my console
http://pastebin.com/XZKpBQ51

**Comment by InventivetalentDev** [comment]
Please provide the image you tried to use.
Also, the error seems to occur on startup, not after you create the image, right?

**Comment by DenDerErn** [comment]
I do not know when the error occured

Heres the image, also tried with a gif
http://i.imgur.com/kAe9iZS.png

**Comment by InventivetalentDev** [comment]
Do you have MapManager and PacketListenerAPI installed?

**Comment by DenDerErn** [comment]
Okay it works now :) I needed to get a newer version of PacketListenerAPI thank you!
