### ISSUE TITLE
plugin not starting

### ISSUE THREAD

**Issue by gmanc2** [InventivetalentDev/AnimatedFrames#20]
## What steps will reproduce the problem?  
1.  Load the server

## What were you expecting to happen? What happened instead?  
The plugin to be enabled
The plugin is not enabled...
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
Command did not appear to work properly but I am running the latest version on spigot 4.3.2
## What Spigot version are you using? *Type /version*  
1.9.4-R0.1-SNAPSHOT 
## What plugins are you using? *Type /plugins*  
[here](https://gyazo.com/a98805dca4398e1afb277183f1eebb0e)
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
[here](http://pastebin.com/gbAyZMG2)
No error log
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No

**Comment by InventivetalentDev** [comment]
No error log? There are **a lot** of errors in this log, you should really update/remove the plugins that cause those.  

But, back to AnimatedFrames: You shouldn't just look for errors if a plugin does not work. (Which is particularly hard if you have a log containing this many errors.)
The plugin tells you in the console what's the problem (it's also on the plugin description page), I'll leave it up to you to find the pretty obvious messages.
