### ISSUE TITLE
AF doesn't support purpur?

### ISSUE THREAD

**Issue by Speedspencer** [InventivetalentDev/AnimatedFrames#200]
## What steps will reproduce the problem?  
1.  use custom jar (purpur)

## What were you expecting to happen? What happened instead?  
I expect to run normally but it did not 
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
AF 4.12.1 Snapshot
## What Spigot version are you using? *Type /version*  
Purpur 1.16.5-R0.1-SNAPSHOT
## What plugins are you using? *Type /plugins*  
90 plugin can't list 
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/9JpqZWnm
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
It did not crash but all the frames seems to be gone

**Comment by InventivetalentDev** [comment]
Use spigot/paper. I don't plan on supporting any custom forks.
