### ISSUE TITLE
AnimatedFrames Exception in thread "pool-27-thread-1"

### ISSUE THREAD

**Issue by SoraCent** [InventivetalentDev/AnimatedFrames#218]
## What steps will reproduce the problem?  
1. Starting the Server

## What were you expecting to happen? What happened instead?  
Excepted is that the Frames are loaded but all Frames are removed and there is an Error in the console

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
4.13.0-Snapshot

## What Spigot version are you using? *Type /version*  
Paper-675 - 1.16.5

## What plugins are you using? *Type /plugins*  
Plugins (93): AdvancedBan, AdvancedFood, AdvancedNMotd, AdvancedPortals, AdvancedRegionMarket, AnimatedFrames*, ArmorStandEditor, AuctionHouse, BannerMaker, BigDoors, BKCommonLib, BlackMarket, Brewery, ChatEx*, Citizens, CitizensText, ClearChat*, ColoredSigns*, CommandSpy*, CrackShot, CraftBook, DeluxeMenus, dtlTraders, dynmap*, EasyElevator, EazyNick, EntityDetection, Essentials, EssentialsProtect, ExplosionReversal, FriendsSpigot, GSit, GtzDoors, HeadDatabase, HolographicDisplays, HomeGUI, HubThat, HyperDrive, Iridescent, IronKeys*, JoinMessagePlus, JukeBox, Karma, LibsDisguises, Lift, Lores*, Lottery, LuckPerms, MapManager, MarriageMaster, McEventCore, Minepacks, MoneyFromMobs, MoneyPouch, MoneyPrinters, Morphy, Multiverse-Core, Multiverse-Inventories, NametagEdit*, NexEngine, NoteBlockAPI, NoTotemHand*, OtherAnimalTeleport, PacketListenerApi*, ParticleHats, PetBlocks*, PlaceholderAPI, PlayerHeads, PlayerVaults, PlayTime*, Plot2Dynmap, PlotSquared, ProtocolLib, QuickBoard*, Seasons, Sentinel, Shop, SimpleSignEditor, Slothgaming, SmokingPipes, SudoSigns, TAB, TCCoasters, TCHangRail, Telecom, TradeSystem, Train_Carts, UltimateTimber, Vault, WirelessRedstone, WorldBorder, WorldEdit, WorldGuard

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/Aew7Spyt

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
It worked before without problem

**Comment by Thornbush42** [comment]
I believe I have the same error, but it seems to coincide with our update to Java 16 also, unclear if this is the cause.

**Comment by SoraCent** [comment]
My Server is still on Java11 so idk if that is the problem

**Comment by TheNety** [comment]
It's most probably caused by changes in Bukkit/Spigot/Paper. For me it started to happen after updating from Paper 1.16.5 build 642 to build 706.
