### ISSUE TITLE
AF cant delete animations

### ISSUE THREAD

**Issue by Bodyash** [InventivetalentDev/AnimatedFrames#22]
afremove code4
Restart server
[10:33:20 INFO]: [AnimatedFrames] Started 'code4' (11/11)

Fix plz :D

**Comment by InventivetalentDev** [comment]
Please check if _/plugins/AnimatedFrames/saves/frames/code4.afd_ still exists when you remove it and check if the _index.afi_ file contains 'code4' after you stop the server.
Also, is it just the 'Started...' message, or is the frame actually still visible ingame?

**Comment by Bodyash** [comment]
code4.afd still exist and  index.afi file contains 'code4'
When i delete code4 for fist time - i`m removed item_frame from wall and restarted server after few days. I can check if code4 still works.

**Comment by Kitt3120** [comment]
I have kinda the same problem

I created some frames but i wanted to remove them all quickly so i unloaded the plugin, deleted the whole AnimatedFrames folder and loaded it again. It says nothing about loading the frames anymore in console but when i do /aflist ingame it says that they are still there! When i try to create another frame with the same name it wont work. When i try to delete them im getting an error.

Ingame
![image](https://cloud.githubusercontent.com/assets/10689811/18010632/95856f3e-6bb1-11e6-8f7b-2aa205e70f06.png)

Console
![image](https://cloud.githubusercontent.com/assets/10689811/18010650/a7bdda42-6bb1-11e6-8670-e13254927ff9.png)


Even deleting the whole AnimatedFrames folder doesnt delete the frames.. and now im not able to delete them from my server anymore. Its annoying cause its still kinda there and i cant create frames with that name anymore.
