### ISSUE TITLE
ConcurrentModificationException when teleporting to another world 

### ISSUE THREAD

**Issue by Dymeth** [InventivetalentDev/AnimatedFrames#227]
I teleported to another world and a second later an exception was shown in the console. I didn't find any other problems.
I tried to repeat these steps several times, but the error did not appear anymore. Most likely, it appears rather rarely. 
When the error occurred and during testing, there were no other players on the server. 

git-Paper-786 (MC: 1.16.5)
AnimatedFrames version 4.13.1-SNAPSHOT
MapManager version 1.8.1-SNAPSHOT

Exception: https://pastebin.com/raw/ymfy9e7M

I'm not sure if this issue is related to AnimatedFrames or MapManager

**Comment by grubtub19** [comment]
This exact exception occurs on my servers as well. 

In this instance, it happened prior to a player joining the server:
https://pastebin.com/raw/jZAx37F0

git-Paper-358 (MC: 1.17.1)
PacketListenerApi v3.9.8-SNAPSHOT
MapManager v1.8.5-SNAPSHOT
AnimatedFrames v4.13.3-SNAPSHOT

Love your work!
