### ISSUE TITLE
Error report, frames doesn't show.

### ISSUE THREAD

**Issue by Daxxas** [InventivetalentDev/AnimatedFrames#23]
## What steps will reproduce the problem?  
1. Have a 1.9.2 spigot server with a frame in the server
2. Run buildtool.jar with the command "java -jar BuildTools.jar --rev 1.9.4" to update the server in 1.9.4
3. The frame should not show up now.

## What were you expecting to happen? What happened instead?  
Expecting : I have 2 frames, I expected them to load. Happened : They doesn't work.
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
4.3.3
## What Spigot version are you using? *Type /version*  
I've switched from 1.9.2 to 1.9.4
## What plugins are you using? *Type /plugins*  
 Plugins (68): ActionAPI, AdvancedAchievements, AnimatedFrames, AreaShop, Auctions, AutoMessage, Bank, BetterChairs, BossBarPlus, CakeClicker, ChatEx, ChestRegen, ChunkUp, Citizens, ColoredNameTags, CommandNPC, CoreProtect, CrazyEnchantments, CreativeParkour, CS-CoreLib, DabCore, DailyRewards, DiceRoller, DungeonsXL, EditableSign, EnderCore, Essentials, EssentialsSpawn, FirstJoinPlus, HolographicDisplays, iConomy, ItemCases, Jobs, LeakParkour, MapManager, MoreItems, Multiverse-Core, Multiverse-Portals, MyCommand, MythicDrops, MythicMobs, NovaGuilds, OpenInv, PacketListenerApi, PermissionsEx, PlugMan, PowerNBT, PressureCommands, ProRecipes, ProtocolLib, pvparena, QuickMarket, SecondChance, ServerSigns, Servertutorial, SilkSpawners, SimpleStaffList, SuperTrails, Tablist, Taxes, TimeIsMoney, TitleAPI, Trading, Vault, VoxelSniper, WorldEdit, WorldEditSelectionVisualizer, WorldGuard
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
http://pastebin.com/k4MRyYEM
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
It worked well in 1.9.2

**Comment by InventivetalentDev** [comment]
Could you post your whole server log, please?
There doesn't seem to be much information what actually caused the issue in the exception you included.

**Comment by Daxxas** [comment]
http://pastebin.com/7Q8YJwY1
here it is, I've started it, and closed it.

**Comment by InventivetalentDev** [comment]
[Resolved](https://www.spigotmc.org/threads/animatedframes-1-8-1-9-1-10.58635/page-45#post-1835820)
