### ISSUE TITLE
Newly generated vanilla maps being overridden 

### ISSUE THREAD

**Issue by Fupery** [InventivetalentDev/AnimatedFrames#27]
## What steps will reproduce the problem?
1. Enable Vanilla Maps in MapManager Config with **allowVanilla: true**
2. Create an animated frame
3. Use an empty map item to create a new map (or call World#createMap in another plugin)
## What were you expecting to happen? What happened instead?

MapManager says "Adding new Map #<mapId> to occupied IDs" in console, but the map produced is overridden with a frame from the animation. Removing all animated frames then logging out and in fixes the map.
## What version of the plugin are you using? _Type /version &lt;Plugin Name&gt;_

AnimatedFrames: 4.3.3, MapManger: 1.2.0, PacketListenerApi: 3.4.4
## What Spigot version are you using? _Type /version_

1.10.2
## What plugins are you using? _Type /plugins_

WorldEdit, PacketListenerApi, MapManager, ProtocolLib, WorldGuard, AnimatedFrames
## Do you have an error log? Use [pastebin.com](http://pastebin.com). _If you're not sure, upload your whole server log_

Nope 
## Did your client crash? _Upload errors in .minecraft/logs/latest.log as well_

Nope
## Additional information?  _(Are you using Bungeecord? Did it work in previous versions? etc.)_

No Bungeecord
MapManager finds occupied map ids fine on enable, it's only a problem when creating new maps while an animation is running.

**Comment by InventivetalentDev** [comment]
Newly created vanilla maps are ignored by MapManager at the moment.
They should work fine after you restart the server.

**Comment by Fupery** [comment]
Thanks for the quick reply, I reported the issue is because it means MapManager is incompatible with one of my plugins, ArtMap (which calls World#createMap to allow players to paint in-game). 

Some of my users would like to use both AnimatedFrames and ArtMap; do you have any plans to support newly created vanilla maps in MapManager in the future?
