### ISSUE TITLE
Images getting mixed up

### ISSUE THREAD

**Issue by zenandreas** [InventivetalentDev/AnimatedFrames#29]
## What steps will reproduce the problem?
1. Create several image frames
2. Look at them like they are paintings
3. 
## What were you expecting to happen? What happened instead?

To look normal, they don't: https://images-1.discordapp.net/.eJwtyEsOgyAQANC7sHeYD4p4mYYgQRMVAtNV07t307d8H_Pul9nModrGZu1-jlT7DkNrjyVDqbVcObZzQKq3jaoxHXd-dFiWsMjMRIIBWdi5f4nzYUVHAb1YRlomwonlRR4YgQTaU8z3B4fuI5Q.-cBJwN2_uyeUgJirj8ViXr8IWYE
## What version of the plugin are you using? _Type /version &lt;Plugin Name&gt;_

4.3.3
## What Spigot version are you using? _Type /version_

http://prntscr.com/cxs5cz
## What plugins are you using? _Type /plugins_

http://prntscr.com/cxs5f8
## Additional information?  _(Are you using Bungeecord? Did it work in previous versions? etc.)_

Just happens randomly, not every time.

**Comment by LaughNgamez** [comment]
Confirming this issue but it seems the dev is short on time/motivation.

**Comment by QueenKisaki** [comment]
I'm having the same issue. I have a total of about 11 frames throughout my server and worlds and they get mixed up and scrambled. Having to relog just to make sure its there which means my players can see them all scrambled too.

**Comment by omega015** [comment]
This is still an issue.

**Comment by Skaizdoesmc** [comment]
Still an issue, most likely unfixable though.
