### ISSUE TITLE
AF stopped animation.

### ISSUE THREAD

**Issue by Bodyash** [InventivetalentDev/AnimatedFrames#3]
## What steps will reproduce the problem?  
1. Teleporting to players
2. changing world
3. else?

i`m using 5 different worlds.
One for spawn (called Empty)
One for adventures (hoth with hothgenerator plugin)
and three worlds (World, world_nether, etc)

Teleporting to them - gone back to spawn - some maps stopped and empty. and only one way to launch frame again - server restart.

**Comment by Bodyash** [comment]
![2016-05-31_23 06 39](https://cloud.githubusercontent.com/assets/2454569/15688792/6c9dbdea-2784-11e6-97d3-2a6b6e43588c.png)

**Comment by InventivetalentDev** [comment]
Ok, does 'empty' mean there is no item in the item frame at all (like the frame on the right), or is the map completely empty? (Would still look like an item frame, but is as big as if it had an image in it)

**Comment by Bodyash** [comment]
If u mousewheel click on empty frame - i will get ItemFrame. So yea, its empty.
Very strange. If i destroy working item frame - and place a new one - image will return, but its not working to stopped working frame.
and again:

![2016-06-01_19 47 43](https://cloud.githubusercontent.com/assets/2454569/15717973/f6fec09e-2831-11e6-9b39-5397b621bb00.png)

**Comment by InventivetalentDev** [comment]
Okay, that's a bit weird. The plugin has a backup system if frames get unloaded and it should restore by itself after a few seconds. Could it just be your players breaking the frames, do you have any protection plugin for that?

**Comment by Bodyash** [comment]
No, any plugin to protect it.

**Comment by Bodyash** [comment]
![2016-06-02_14 15 43](https://cloud.githubusercontent.com/assets/2454569/15743221/91c99852-28cc-11e6-921a-082b9d30413c.png)

:D

**Comment by InventivetalentDev** [comment]
What plugin(s) are you using to teleport and change worlds? (Just post all plugins if you're not sure)

**Comment by Bodyash** [comment]
Multiworld (/mw goto world for example)
EssentialsX (modified essentials) https://github.com/drtshock/Essentials
RandomTeleport for /rtp (http://dev.bukkit.org/bukkit-plugins/random-teleport/)
Its all

**Comment by Bodyash** [comment]
![2016-06-04_04 08 15](https://cloud.githubusercontent.com/assets/2454569/15796650/2405b80c-2a0a-11e6-9291-f17447b69064.png)
And again. U can just look at my plugin list.

**Comment by InventivetalentDev** [comment]
I'm sorry, but I can't seem to replicate your issues. Teleporting / changing worlds works absolutely fine for me.  
I can only suggest you try the plugin on a separate server without plugins and see if it works there. If it does, it's an incompatibility with one of your plugins. (I don't really have the time to test it with all of the plugins on your server)

**Comment by Bodyash** [comment]
Maybe protocollib? MassiveCore? Craftbook?
Can u add a command to fire all animations and start new one. Cause its very painfuly to restart the server. And i think its not tp problem.

**Comment by Bodyash** [comment]
1 more. I cant put any items in ItemFrame, where animation stopped working.

**Comment by Bodyash** [comment]
![2016-06-05_22 16 33](https://cloud.githubusercontent.com/assets/2454569/15807621/6e90b752-2b6b-11e6-8286-017d4df639e9.png)
And one more. If this is gonna be broken - all 3 itemFrames Will Be empty.
Maybe some problems with WorldGuard private plugin?

**Comment by InventivetalentDev** [comment]
Could you please upload some of the save-files of the empty maps? I just had a similar issue and the file seems a bit corrupted.

**Comment by Bodyash** [comment]
https://www.dropbox.com/s/9ixuw0vgry7o1qg/images.zip?dl=0
For example

**Comment by InventivetalentDev** [comment]
Sorry, I meant the save files (/plugins/AnimatedFrames/saves/xyz.afd).

**Comment by Bodyash** [comment]
https://www.dropbox.com/s/lwg3rmba7fbr8sd/saves.zip?dl=0

**Comment by InventivetalentDev** [comment]
Your saves seem fine, so it's caused by something else. I'll keep looking for a solution.

**Comment by Bodyash** [comment]
4 this moments when i  migrate to 1.10.2 a have a lot problems. But i temporary removed libsdiguises and echopet plugin + changed SkinsRestorer to SkinChanger plugin. I now AF working good. No images dissapear for 12+ hours uptime.
But i have some crashes. Can u look into this thread? https://www.spigotmc.org/threads/server-crash-need-help.158763/

AND SORRY FOR MY ENGLISH :C

**Comment by InventivetalentDev** [comment]
So it's working now after you removed some plugins? It must have been an incompatibility with those plugins then (although I have no idea how disguise or skin plugins could interfere maps).

**Comment by Bodyash** [comment]
Maybe Spigot version change, maybe some plugins (Updated a lot of them when migrated to 1.10.2)

**Comment by Bodyash** [comment]
Nope, started dissapear again. Maybe some problems with connection?

**Comment by InventivetalentDev** [comment]
So they disappeared after restarting now? Could you please upload your save files again?

**Comment by Bodyash** [comment]
http://rgho.st/private/7rNTLzzwl/f6dbbf4a5b64c08263d104fa6c872360

All folder.

They dissapear sometimes again, and i need to restart to load it again. I think maybe some problems with connections? Server in France (OVH host), i`m in Ukraine. 1 timeout to send image packet to me - and i will never see this image. Even if relogin. Maybe add some debug info? And log it in AnimatedFrames.log file.?

**Comment by InventivetalentDev** [comment]
The saves seem fine.  
Could be a connection issue. What sort of debug info would you want? I don't quite see how that would help.

**Comment by Bodyash** [comment]
For any animations send packets log, maybe? Error printStackTrace?

**Comment by InventivetalentDev** [comment]
I don't think that would really help. It's not like the packet is actively 'hiding' errors, if there were actual errors, you would certainly notice them.  
So, I still have no idea what causes this, it seems sort of random. I still feel like this is an incompatibility with one of your plugins, since you're the only one reporting issues like this.

**Comment by Bodyash** [comment]
Get some problems with MythicMobs, kicked from server and reconecting back:

http://pastebin.com/ccngD675

**Comment by InventivetalentDev** [comment]
I closed this issue twice. Please create a separate one.
