### ISSUE TITLE
Crash when removing a frame

### ISSUE THREAD

**Issue by MADS0LADEN** [InventivetalentDev/AnimatedFrames#33]
## What steps will reproduce the problem?  
1. Create gif frame
2. Remove gif frame
3. Client crash

## What were you expecting to happen? What happened instead?  
Remove the frame without crashing my 1.11.2 client (it was removed when rejoining)

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
4.4.1-SNAPSHOT (3.5.1-SNAPSHOT PacketListenerAPI)

## What Spigot version are you using? *Type /version*  
git-Spigot-7d78b81-e232e15 (MC: 1.11.2)

## What plugins are you using? *Type /plugins*  
![image](https://cloud.githubusercontent.com/assets/4103363/22559337/106b8a66-e971-11e6-879a-af3e14f3088f.png)

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*
https://hastebin.com/taxulenero.vbs

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
![image](https://cloud.githubusercontent.com/assets/4103363/22559357/1eed3d96-e971-11e6-9a1e-8a16dc29ceaa.png)

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Nope, none of that.

**Comment by MADS0LADEN** [comment]
I only crash when the chunk is loaded where the frame is.

**Comment by InventivetalentDev** [comment]
Please try the [1.3.3-SNAPSHOT](https://github.com/InventivetalentDev/MapManager/releases/tag/1.3.3-SNAPSHOT) of MapManager, should be fixed there.
