### ISSUE TITLE
No java.lang.NoSuchFieldException

### ISSUE THREAD

**Issue by Rocologo** [InventivetalentDev/AnimatedFrames#35]
## What steps will reproduce the problem?  
1.  Each time I try to create an AnimatedFrame I get this error in the log. (http://pastebin.com/4Uqsb3nx) after running the command I get this error in the console, and no animated gif inside minecraft
2. I have tried to delete both AnimatedFrames and MapManager folders and start on a fresh, but no luck creating the animation.
3. This is the line I try to run /afcreate Angel https://dl.dropboxusercontent.com/u/36067670/minecraft/Animated%20gif/8808%20-%20animated_gif%20doctor_who%20tagme%20weeping_angel.gif

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  

AnimatedFrames version 4.4.2-SNAPSHOT
MapManager version 1.3.4-SNAPSHOT
PacketListenerApi version 3.5.2-SNAPSHOT
This server is running CraftBukkit version git-Spigot-65a0347-a552117 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*

http://pastebin.com/4Uqsb3nx

**Comment by Rocologo** [comment]
This is still a problem @InventivetalentDev it would be nice if you could find some time to look at the problem. 

None of mine animated gifs does work and I cant create new ones :-( I miss this plugin on my server.

**Comment by InventivetalentDev** [comment]
Please provide the server version and the plugins you're using

**Comment by Rocologo** [comment]
Spigot 1.11.2
07.04 20:00:53 [Server] INFO This server is running CraftBukkit version git-Spigot-625bc00-41a7d14 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

Plugins
07.04 20:02:12 [Server] INFO Plugins (82): CleanroomGenerator, TerrainControl, MYSlots, PlaceholderAPI, MythicLib, PlugMan, Herobrine, WorldResourcepacks, EditableSign, GameModeControl, ParticleLIB, WooMinecraft, LightAPI, dynmap, EmptyWorldGenerator, WorldBorder, ActionHealth, Votifier, ProtocolLib, LibsDisguises, TARDISChunkGenerator, FastAsyncWorldEdit, OpGuard, PermissionsEx, EffectLib, LongerMessages, ServerListPlus, GAListener, Vault, PerWorldInventory, LWC, ASkyBlock, WorldEdit, CityWorld, Essentials, TARDISWeepingAngels, SimpleClans, Citizens, OnTime, EssentialsChat, LogBlock, PlotSquared, WorldGuard, EssentialsXMPP, EssentialsProtect, EssentialsGeoIP, EssentialsAntiBuild, Shop, ServerSigns, EssentialsSpawn, TitleManager, MCBans, OnSign, Dynmap-WorldGuard, Multiverse-Core, Sentinel, BiomeGenerator, Plot2Dynmap, CraftBook, Multiverse-Portals, GriefPrevention, GiantTrees, ChestShop, MobArena, RegionForSale, HolographicDisplays, MythicMobs, Multiverse-SignPortals, ProtectionLib, RandomTeleport, Multiverse-NetherPortals, CratesPlus, WirelessRedstone, MyPet, MobHunting, TARDIS, JDynmapGriefPrevention, Quests, FurnitureLib, Dynmap-TARDIS, DiceFurniture, DiceGraveStoneOfDeath

**Comment by Rocologo** [comment]
Packetlisterner and mapmanager  i your newest snapshot releases on github.

**Comment by Rocologo** [comment]
Is there anything I can do to help you finding this bug?

**Comment by Rocologo** [comment]
Same bug https://github.com/InventivetalentDev/MapManager/issues/6

**Comment by Rocologo** [comment]
I have finally found the plugin which was conflicting with PacketListerner, breaking PacketListner+MapManager+animatedframes. 

When I install ParticleAPI 2.1.1 it breaks PacketListener 3.6.0
