### ISSUE TITLE
AnimatedFrames don't work !

### ISSUE THREAD

**Issue by Clemdu63** [InventivetalentDev/AnimatedFrames#38]
## What steps will reproduce the problem?  
1. /afcreate test https://media2.giphy.com/media/zDuStFVpRJIZ2/giphy.gif
2. I select corners
3. Nothing happend

## What were you expecting to happen? What happened instead?  
Nothing happend I can't see the animation 

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
4.4.2-SNAPSHOT
## What Spigot version are you using? *Type /version*  
1.10
## What plugins are you using? *Type /plugins*  
199 plugins
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
Nope
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
Nope
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*

The command /afremove don't work too (Nothing work in this plugin it's cool !)

sorry for my english i'm french

**Comment by Clemdu63** [comment]
???

**Comment by InventivetalentDev** [comment]
Do you get any messages? While creating the frame?  
If you don't get any response after creating the image, there should be some output in the console.

**Comment by Clemdu63** [comment]
Yes I have the message which say everything work the frame start playing or something like that

**Comment by FFY00** [comment]
There are no errors in the console?
