### ISSUE TITLE
too many arguments?

### ISSUE THREAD

**Issue by dimdimak1** [InventivetalentDev/AnimatedFrames#39]
## What steps will reproduce the problem?  
1. /af create nyan_cat http://gph.is/1xwrShL
2. too many argumenst
3.

**Comment by InventivetalentDev** [comment]
Write /afcreate without a space

**Comment by dimdimak1** [comment]
i solved it but i now have another problem. When i do this command with a gif 200*200 the plugin doesnt show the gif
