### ISSUE TITLE
Creating default vanilla maps.

### ISSUE THREAD

**Issue by Bodyash** [InventivetalentDev/AnimatedFrames#4]
## What steps will reproduce the problem?
1. Get Empty map
2. Right CLick
3. Nice, u have an image from AnimatedFrames. I have 7 images - and i must use 7 maps, get all images, and then, i can create vanilla map of terrain.

**Comment by InventivetalentDev** [comment]
Is 'allowVanilla' enabled in the MapManager configuration?

**Comment by Bodyash** [comment]
Yeap

**Comment by InventivetalentDev** [comment]
Do you get a 'Adding new Map #x to occupied IDs.' in the console?  
MapManger won't refresh existing maps on its own, but it should ignore the maps you created after you relog/restart your Minecraft.

**Comment by Bodyash** [comment]
I will check it.

**Comment by Mabus13** [comment]
Same problem.
And also use villager maper useles. Because all maps forests and oceans is image of AF not map.
