### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dimdimak1** [InventivetalentDev/AnimatedFrames#40]
## What steps will reproduce the problem?  
1. /afcreate nyan_cat (link)
2. the other steps
3. When i do this command with a gif 200*200 the plugin doesnt show the gif

**Comment by InventivetalentDev** [comment]
Would you mind actually filling in the the answers to the provided questions?
They are there for a reason.

**Comment by raga70** [comment]
the plugin dont even generates a folder it stays in red when i type /plygins to any comand says no such comand by the way im runing 1.11.1

**Comment by InventivetalentDev** [comment]
Then you probably didn't install one of the dependencies. Something I could've told you directly if you answered the questions in the template, specifically the question about your installed plugins.

**Comment by dimdimak1** [comment]
i'm on 1.8.9 the same with raga70. Do you have a version which works on 1.8

**Comment by InventivetalentDev** [comment]
Just answer the questions of the template, please.

**Comment by dimdimak1** [comment]
ok

**Comment by dimdimak1** [comment]
sorry i was in the wrong plugin issue page
