### ISSUE TITLE
WARN Invalid SemVer versions specified [450-SNAPSHOT] [450-SNAPSHOT]

### ISSUE THREAD

**Issue by Jav0330** [InventivetalentDev/AnimatedFrames#46]
1) get spigot-1.12.0-20170608a.jar , AnimatedFrames 4.50, PacketListenerAPI 3.6.0-SNAPSHOT, MapManager 1.4.0-SNAPSHOT

2. Boot Server

## Do you have an error log? 19.07 08:18:41 [Server] WARN at java.lang.Thread.run(Thread.java:745)
19.07 08:18:41 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
19.07 08:18:41 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
19.07 08:18:41 [Server] WARN at org.inventivetalent.animatedframes.AnimatedFrame.run(AnimatedFrame.java:137)
19.07 08:18:41 [Server] WARN at org.inventivetalent.animatedframes.AnimatedFrame.scaleImage(AnimatedFrame.java:240)
19.07 08:18:41 [Server] WARN java.lang.NullPointerException
19.07 08:18:41 [Server] WARN Exception in thread "pool-40-thread-6" 
19.07 08:18:41 [Server] INFO Animation length for 'biker' is zero. Creating non-animated image.
19.07 08:18:41 [Server] INFO Downloaded 'https://www.dropbox.com/s/nrti75qsfcbtvd9/bikerecipe.gif' to 'plugins/AnimatedFrames/images/aHR0cHM6Ly93d3cuZHJvcGJveC5jb20vcy9ucnRpNzVxc2ZjYnR2ZDkvYmlrZXJlY2lwZS5naWY='.
19.07 08:18:41 [Server] WARN at java.lang.Thread.run(Thread.java:745)
19.07 08:18:41 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
19.07 08:18:41 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
19.07 08:18:41 [Server] WARN at org.inventivetalent.animatedframes.AnimatedFrame.run(AnimatedFrame.java:137)
19.07 08:18:41 [Server] WARN at org.inventivetalent.animatedframes.AnimatedFrame.scaleImage(AnimatedFrame.java:240)
19.07 08:18:41 [Server] WARN java.lang.NullPointerException
19.07 08:18:41 [Server] WARN Exception in thread "pool-40-thread-3" 
19.07 08:18:41 [Server] INFO Animation length for 'brec' is zero. Creating non-animated image.
19.07 08:18:41 [Server] INFO Downloaded 'https://www.dropbox.com/s/8cb41msjw8d87kf/brec.gif' to 'plugins/AnimatedFrames/images/aHR0cHM6Ly93d3cuZHJvcGJveC5jb20vcy84Y2I0MW1zanc4ZDg3a2YvYnJlYy5naWY='.
19.07 08:18:41 [Server] INFO Started '4p' (3/5)
19.07 08:18:40 [Server] INFO Started '4b' (2/5)
19.07 08:18:40 [Server] INFO Started '4g' (1/5)
19.07 08:18:39 [Server] INFO Loaded 5 frames.
19.07 08:18:39 [Server] INFO Loading data...
19.07 08:18:38 [Server] INFO No update was found, you are running the latest version. Will check again later.
19.07 08:18:37 [Server] INFO Checking for updates via Spigot...
19.07 08:18:35 [Server] INFO The plugin is up-to-date.
19.07 08:18:35 [Server] WARN Invalid SemVer versions specified [450-SNAPSHOT] [450-SNAPSHOT]

## Did your client crash? no

I get errors that the gif in question not being an animation, although it most certainly is animated. Not exactly sure why it doesnt work. 
![brec](https://user-images.githubusercontent.com/17805690/28372348-773222e4-6c6d-11e7-9c5d-6486743af680.gif)

**Comment by Jav0330** [comment]
Any insight anyone could provide would be greatly appreciated!

Thanks in advance..

**Comment by InventivetalentDev** [comment]
Please try another image host / make sure you use the direct link to the image. The link you used points to a dropbox HTML page, containing the original image at https://dl.dropboxusercontent.com/content_link/mFhxD9Q46xVWixaxnn6GPVmw1dJChZnLWgKnD2sDf3b7Ryn88TQwgvtX3JI8Dhla/file?dl=0&duc_id=Wmukv6lu6YFAPHLXRhYCGu2KNFZPtzYoMbLUvHLEJtRAcFDjMileLGCpiklKWiTE&raw=1&size=2048x1536&size_mode=3

**Comment by InventivetalentDev** [comment]
Also, relating to the issue's title, it's only a _warning_ log message, so just ignore it.

**Comment by smmmadden** [comment]
I see the same WARN message for SpigetUpdate Invalid SemVer versions specified [450-SNAPSHOT] [450-SNAPSHOT] for BungeeCord/Spigot 1.12.1 servers. 

Are there any plans to fix the issue with the validation of the version?  Seems this has been present for a couple months now and 1.12.2 is slated to be released tomorrow. :-)  Thanks -Steve

**Comment by Yukyxy** [comment]
in 1.131 too 
[19:14:46] [Craft Scheduler Thread - 45/WARN]: [SpigetUpdate] Invalid SemVer versions specified [470-SNAPSHOT] [470-SNAPSHOT]

**Comment by smmmadden** [comment]
If it is stale, it is stale because @InventivetalentDev has not fixed it in any recent builds that could be downloaded by users.

**Comment by InventivetalentDev** [comment]
This should be fixed in one of the recent versions.

**Comment by smmmadden** [comment]
It is, thank you! :-)
