### ISSUE TITLE
Image doesn't come up

### ISSUE THREAD

**Issue by jariahtiainen** [InventivetalentDev/AnimatedFrames#47]
## What steps will reproduce the problem?  
1. I had a wall with item frames 5*5, did the afcreate command
2. right clicked the corners
3. 

## What were you expecting to happen? What happened instead?  
No image appeared

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
4.5.0-SNAPSHOT

## What Spigot version are you using? *Type /version*  
CraftBukkit version git-Spigot-99c2a37-3819f8d (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

## What plugins are you using? *Type /plugins*  
Plugins (35): icJukeBox, CleanroomGenerator, WorldEdit, CityWorld, PacketListenerApi, Lift, Dispensator, BetterChairs, EasyCarts, MapManager, WorldGuard, ProtocolLib, Multiverse-Core, LibsDisguises, SkinsRestorer, VoxelSniper, PermissionsEx, KonseptGate, Multiverse-Portals, Vault, GriefPrevention, AreaShop, UltraCosmetics, Essentials, pvparena, AnimatedFrames, MobArena, Jobs, ShowCaseStandalone, CreativeParkour, HolographicDisplays, LockettePro, HeavySpleef, ServerSigns, HolographicExtension

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/y2WAsPUZ

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
no

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
no bungeecord

## The image I used: https://media.giphy.com/media/l4FGzIZUKIsc2kteE/giphy.gif

**Comment by InventivetalentDev** [comment]
Please try another image provider. Giphy doesn't work properly, since the linked image isn't the original source.

**Comment by smmmadden** [comment]
I was using the same website and can confirm the same behavior.  I downloaded the giphy image locally and used a url to my webserver and it worked. :-)  I'm using 1.12.1 of the same Bungee/Spigot servers.

**Comment by jariahtiainen** [comment]
Yes, it's working now! Thanks!
