### ISSUE TITLE
Commands dont work

### ISSUE THREAD

**Issue by MonStalone** [InventivetalentDev/AnimatedFrames#49]
## What steps will reproduce the problem?  
1. typed /afhelp
2. didn´t work

## What were you expecting to happen? What happened instead?  
Commands work. But they just say type /help
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
4.5.0 SNAPSHOT
## What Spigot version are you using? *Type /version*  
1.12-R0.1-SNAPSHOT
## What plugins are you using? *Type /plugins*  
WorldEdit Mypet IDisguise CS-CoreLib SlimeFun Image on map ExoticGarden PacketListenerAPI MapManager AnimatedFrames
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log* 
  https://pastebin.com/mvs4Teb1

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Not using Bungeecord first time using it

**Comment by MonStalone** [comment]
Please help

**Comment by InventivetalentDev** [comment]
Seems like you're not using Spigot
