### ISSUE TITLE
Console error spam from ViaVersion and inability to remove images in game once created

### ISSUE THREAD

**Issue by TheZenKitteh** [InventivetalentDev/AnimatedFrames#51]
## What steps will reproduce the problem?  
Image Removal
1. Add an image
2. Try to remove it

Console errors
1. Fly around with AnimatedFrames loaded
2. See a bunch of errors in the console

## What were you expecting to happen? What happened instead?  
For the image removal, I expected removing the image in game to remove the image. It does not.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
4.5.0-snapshot

## What Spigot version are you using? *Type /version*  
Spigot 1.12 BuildTools: 60

## What plugins are you using? *Type /plugins*  
A bunch, this doesn't seem related to other plugins.

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/raw/DfaCdqEn

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
It seems at this time the issue with the console errors was due to a large .gif file. I removed it via /afremove name but it didn't actually remove the image. I just manually found and deleted the image and reloaded animatedframes and so far the error seems gone. I'll report back if it's not. It seems impossible to remove any images once created from in game. To remove an image, I have to manually delete it and the filenames of the images don't make this easy.

When trying to remove an image, this is the error:
https://pastebin.com/raw/FdLtfunj

Also, manually removing the image doesn't remove the image from the /aflist

**Comment by InventivetalentDev** [comment]
Well, in the main "error" you posted, I can only see a bunch of _warnings_ from ViaBackwards. Since they're only warnings (and nothing this plugin causes directly), I don't think you have to worry about it too much.  

As for the delete issue: don't use reload. Restart the server, please.
