### ISSUE TITLE
Plugin doesn't work in 1.12.1

### ISSUE THREAD

**Issue by thebastien007** [InventivetalentDev/AnimatedFrames#53]
## What steps will reproduce the problem?  
1. install the AnimatedFrales on spigot server
2. Run command /afcreate test (link...)
3. The image doesn't load

## What were you expecting to happen? What happened instead?  
No image load
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
4.5.0-Snapshot
## What Spigot version are you using? *Type /version*  
Spigot 1.12.1
## What plugins are you using? *Type /plugins*  
Essentials, Vault,Skirpt, PacketListener (3.6.0-Snapshot), MapManager (3.6.0-snapshot),...
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
[https://pastebin.com/R0Mia3iR](https://pastebin.com/R0Mia3iR)

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
I use Bungeecord in 1.12.1. Just the image doesn't load with 1.12.1 version

**Comment by TechdudeGames** [comment]
I had the same issue as you. I found that the reason it doesn’t work is that the link you provided as a source link, when downloaded, is not just the gif but the website (With the html) on it. I would try downloading the image onto the server locally then passing /afcreate the tile path+name of it, which should fix the issue.
