### ISSUE TITLE
Creating maps instead creates AnimatedFrames images

### ISSUE THREAD

**Issue by TheZenKitteh** [InventivetalentDev/AnimatedFrames#54]
## What steps will reproduce the problem?  
1. Get an empty map
2. Try to create a map
3. Get something other than map

## What were you expecting to happen? What happened instead?  
To get a map

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
AnimatedFrames v4.5.0-SNAPSHOT
MapManager v1.4.0-SNAPSHOT

## What Spigot version are you using? *Type /version*  
git-Spigot-65e8124-963b19c (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

## What plugins are you using? *Type /plugins*  
Too many to list

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
No errors in log relating to map manager or animated frames

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
MapManager config:
https://pastebin.com/raw/PMukL5WV

No errors in the console.

**Comment by colinrgodsey** [comment]
yea, same here =\ definitely a shame
