### ISSUE TITLE
too many Args?

### ISSUE THREAD

**Issue by JunkynioyPH** [InventivetalentDev/AnimatedFrames#57]
## THING IS...
i did /afcreate [image] then the full path of the img:
C:\Users\PERSON\Desktop\Bukkit Server (Premade) 1.12.2\AFGif-Pics\[IMG]

## What were you expecting to happen? What happened instead?  
do the magic of the command                    too many args 5>2 then invalid path
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
1.12.2 MC | 4.5.0 SNAPSHOT
## What Spigot version are you using? *Type /version*  
-not spigot- but its bukkit (probably not the correct site but i will do it anyways)
## What plugins are you using? *Type /plugins*  
animatedFrames
Autosaveworld
choptree
clearlag
coloredtags
customenchantments
customrecepies
essentialsX and Xchat and XProtect and Xspawn
healthbar
lightchatbubbles
mapmanager
minepacks
packetlistener
permissionsEx
plugincontsructorAPI
shopkeepers
silkspawners
vault
worldedit
(thats all of it)
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*
  
====no i did not

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
Nope
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
nothing else
![few vteyt](https://user-images.githubusercontent.com/33281422/32601426-8898a8dc-c57d-11e7-81f6-d5c39e678ec8.PNG)

**Comment by InventivetalentDev** [comment]
Don't use spaces in the file path.

**Comment by InventivetalentDev** [comment]
Or just upload the image, e.g. to Imgur.
