### ISSUE TITLE
.GIF not creadet

### ISSUE THREAD

**Issue by Felix5566** [InventivetalentDev/AnimatedFrames#59]
## What steps will reproduce the problem?  
1. gif pictures not work, but png works

## What were you expecting to happen? What happened instead? 
no picture was creadet
https://i.imgur.com/eiUcg6n.png

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
https://i.imgur.com/jTEEZz3.png

## What Spigot version are you using? *Type /version*  
https://i.imgur.com/ScIu9Y5.png

## What plugins are you using? *Type /plugins*  
https://i.imgur.com/Lc88bKE.png

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/d7kDN0Fm

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
no

## What is inside of the config.yml? Use [pastebin.com](http://pastebin.com). */plugins/AnimatedFrames/config.yml*
https://pastebin.com/047KmMN5

**Comment by TechdudeGames** [comment]
I had the same issue as you with the NPE. I found that the reason it does that is when the link you provided as a source link, when downloaded, is not just the gif but the website (With the html) on it. I would try downloading the image onto the server locally then passing /afcreate the tile path+name of it, which should fix the issue.

Giffy is terrible at providing gif links that don’t have html intermixed with it

**Comment by InventivetalentDev** [comment]
Please use a site other than giphy to get your GIFs and make sure you get the actual source image, as mentioned above.
