### ISSUE TITLE
BungeeCord Animated Frames issue?

### ISSUE THREAD

**Issue by KD181999** [InventivetalentDev/AnimatedFrames#6]
## What steps will reproduce the problem?
1. BungeeCord server setup
2. Images in the hub
3. Images in another server
## What were you expecting to happen? What happened instead?

Expected the images to work perfectly on both hub and second server, however image because distorted and mixed up with hub server images as shown here: http://prntscr.com/bgseoo
## What version of the plugin are you using? _Type /version &lt;Plugin Name&gt;_

4.3.1
## What Spigot version are you using? _Type /version_

Spigot R0.1 1.9.4
## What plugins are you using? _Type /plugins_

http://prntscr.com/bgsget
## Do you have an error log? Use [pastebin.com](http://pastebin.com). _If you're not sure, upload your whole server log_

No errors.
## Did your client crash? _Upload errors in .minecraft/logs/latest.log as well_

No.
## Additional information?  _(Are you using Bungeecord? Did it work in previous versions? etc.)_

BungeeCord Network.
1.9.4

**Comment by dvarnai** [comment]
I can confirm this. The issue is probably client side, reconnecting to the server fixes it.

**Comment by KD181999** [comment]
@InventivetalentDev Could we have a fix for this?

**Comment by InventivetalentDev** [comment]
@KD181999 Could you have some patience, please? Thank you.

**Comment by dvarnai** [comment]
The issue is caused by conflicting map ids across servers. I compiled my own version of mapmanager that used random map ids and the issue is gone, although obviously not a proper solution. is it possible to overwrite the client side cache somehow?

**Comment by InventivetalentDev** [comment]
So, I've been trying to come up with a solution for this, but the client's map cache seems to have a very odd behaviour. It doesn't seem to care about any content updates for the images.  
@dvarnai Random IDs is unlikely to not cause any conflicts with different images if you have multiple frames, which would then lead to currently non-existent issues on servers without Bungeecord. It'd also mess up vanilla map generation once again.  
I will keep trying to trick the client into resetting its cache, but I can't provide a solution for this at the moment.

**Comment by dvarnai** [comment]
@InventivetalentDev what do you mean? id conflicts can still be resolved on the same server, it would only reduce the chance of conflicts network-wide. heres what i did:

`	public short getNextFreeIdFor(Player player) throws MapLimitExceededException {
		Set<Short> occupied = getOccupiedIdsFor(player);
		//Add the 'default' occupied IDs
		occupied.addAll(OCCUPIED_IDS);

		ArrayList<Short> allIDs = new ArrayList<Short>();
		for(int i=0;i<=Short.MAX_VALUE;++i) {
			allIDs.add((short)i);
		}
		allIDs.removeAll(occupied);

		if(allIDs.size() == 0) {
			//If we end up here, this player has no more free ids. Let's hope nobody uses this many Maps.
			throw new MapLimitExceededException("'" + player + "' reached the maximum amount of available Map-IDs");
		}

		return allIDs.get(rng.nextInt(allIDs.size()));
	}`

**Comment by InventivetalentDev** [comment]
@dvarnai Ah, I see. I though you were going for completely random ids. I'll give it a try.

**Comment by KD181999** [comment]
Any news on this issue?

**Comment by InventivetalentDev** [comment]
@KD181999 The fourth message above this one.
