### ISSUE TITLE
Gifs are loading but images not

### ISSUE THREAD

**Issue by Bubenik1** [InventivetalentDev/AnimatedFrames#63]
## What steps will reproduce the problem?  
1. Upload a png image to imgur.
2. Run the create command in game.
3. Follow the steps your provided basicly

## What were you expecting to happen? What happened instead?  
That the image would load, as gifs does whitout a problem
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
Latest
## What Spigot version are you using? *Type /version*  
1.12.2
## What plugins are you using? *Type /plugins*  
None that would interfere with it.
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/Ci4weJEc

**Comment by InventivetalentDev** [comment]
Use the direct link to the image. You used the link to the imgur HTML page. (i.e. right-click the image and click "Copy link address")
