### ISSUE TITLE
The plugin won't work

### ISSUE THREAD

**Issue by LielAmarScoRpyoN** [InventivetalentDev/AnimatedFrames#64]
## What steps will reproduce the problem?  
1. 
2. 
3. 

## What were you expecting to happen? What happened instead?  
I was expecting the image to show up, but it didn't. The frames were still visible and no image was shown.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
Latest

## What Spigot version are you using? *Type /version*  
1.8.8-R0.1

## What plugins are you using? *Type /plugins*  
My core (which shouldn't affect it), my hub plugin (same), PEX, Citizens, ViaVersion, NametagEdit, HolographicDisplays, Tablist, BuycraftX, Votifier, Superbvote
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
No
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No & No errors
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Yes, I am using Bungeecord.
I didn't try it in previous versions.

**Comment by preterive** [comment]
same in 1.12.2
