### ISSUE TITLE
Suggestion: Advance Frame by Frame

### ISSUE THREAD

**Issue by adamlaughlin** [InventivetalentDev/AnimatedFrames#65]
I really like Melerpe's new feature, nice update!
Having a command to just advance to the next frame would be great for use in custom commands, skripts, etc.
Giving other plugins access to a command like that allows condensing static frames into an animated frame to reduce lag caused by all the tile entities some large map setups have.
Or enable cool parallax effects as users walk towards and away.. just a lot of new mapmaking abilities would be opened up with that one command.

**Comment by InventivetalentDev** [comment]
The idea does sound awesome for custom maps! I'll look into a way of adding something like that.

**Comment by InventivetalentDev** [comment]
Should be available in the latest version! :)
