### ISSUE TITLE
Create not the gif animation - NullPointerException

### ISSUE THREAD

**Issue by JDittmerCOM** [InventivetalentDev/AnimatedFrames#66]
## What steps will reproduce the problem?  
1. /afcreate Nyan https://media3.giphy.com/media/sIIhZliB2McAo/giphy.gif

## What were you expecting to happen? What happened instead?
![javaw_2018-02-25_23-01-13](https://user-images.githubusercontent.com/11929467/36647042-db1e38d6-1a7f-11e8-8b35-41d687ed8abe.png)
And now nothing happens unless you get an error message in the console > see "**Do you have an error log?**"

## What version of the plugin are you using?
AnimatedFrames 4.6.0-SNAPSHOT
MapManager 1.4.0-SNAPSHOT
PacketListenerAPI 3.6.0-SNAPSHOT

## What Spigot version are you using?
1.12.2-R0.1-SNAPSHOT

## What plugins are you using?
AnimatedFrames_v4.6.0-SNAPSHOT.jar
MapManager_v1.4.0-SNAPSHOT.jar
PacketListenerAPI_v3.6.0-SNAPSHOT.jar

## Do you have an error log?
https://pastebin.com/raw/tCQDzYSX

## Additional information?
No. It was tested on my test server.

**Comment by TechdudeGames** [comment]
I had the same issue as you with the NPE. I found that the reason it does that is when the link you provided as a source link, when downloaded, is not just the gif but the website (With the html) on it. I would try downloading the image onto the server locally then passing  /afcreate the tile path+name of it, which should fix the issue.

**Comment by TechdudeGames** [comment]
giffy is terrible at having links to gif with only the gif

**Comment by InventivetalentDev** [comment]
yep, giphy links are a bit weird. You need to make sure you have the link to the actual source file.
