### ISSUE TITLE
Feature Request: Command to set an existing frame to a new image

### ISSUE THREAD

**Issue by ghost** [InventivetalentDev/AnimatedFrames#67]
Hey Inventivetalent,

Can you add a command like /afset <name of the existing frame> <image> so you can change frames from command blocks for example?

Thanks in advance!

**Comment by InventivetalentDev** [comment]
That's not really possible the way the plugin is designed, unfortunately. 
I'll consider the idea in case I ever rework the internals in the future, though!

**Comment by InventivetalentDev** [comment]
Added the `/afcontent` command in a recent update :)
