### ISSUE TITLE
Strange looking pictures and animations

### ISSUE THREAD

**Issue by LosTigeros** [InventivetalentDev/AnimatedFrames#69]
## What steps will reproduce the problem?  
1.  Just use the latest version

## What were you expecting to happen? What happened instead?  
So I've created the images from URL and colors on them are idk like `compressed` or something.
And to compare...
It should look like that: http://www.youtube.com/watch?v=tj9CYlxHgc0
But it looks like that: https://youtu.be/z14Is1-mUAg

Another example:
It should look like that:
![original](https://repo.mplauncher.pl/fun/wla/serverimages/Welcome_to_the_WLA_Universe_Sample_NT.png)
And:
![looksbadman](https://user-images.githubusercontent.com/6253928/37877256-717b3f0c-3058-11e8-9866-d52b2bdddee9.jpg)
![2](https://user-images.githubusercontent.com/6253928/37877277-d2c18cd0-3058-11e8-82eb-7499f25b8062.jpg)

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
4.6.0-SNAPSHOT

## What Spigot version are you using? *Type /version*  
git-Spigot-c3093ef-3fed09c (MC: 1.12.2)

## What plugins are you using? *Type /plugins*  
```
AsyncWorldEditInjector, Bookshelves, dewdd_empty, SaturationPreview, PacketListenerApi, PlugMan, MapManager, ProtocolLib, Multiverse-Core, SkinsRestorer, MVdWPlaceholderAPI, AsyncWorldEdit, PermissionsEx, FeatherBoard, TAB, Vault, WorldEdit, Essentials, AnimatedFrames, Mine, HolographicDisplays, WorldGuard, Citizens, IslandWorld, DiscordSRV, EssentialsChat, Shop, IslandWorldChallenges, EssentialsSpawn, HolographicScoreboard, ChestShop, AuthMe, SBFB
```

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
No.

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No.

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Im using latest version of bungeecord.

**Comment by Adam759** [comment]
Minecraft has a very limited color space, so when images are imported, it averages and approximates the original colors of the image to fit the color space of Minecraft, thus, as you said, compressing the colors. There is no way around this being it is the design of the game itself.

**Comment by LosTigeros** [comment]
Okay, but why nyan cat animation doesn't look like on original video?

**Comment by Adam759** [comment]
The colors that maps use must be more compressed than the color space then, I didn't realize the background was terracotta. If you put in the nyan cat and get really close, you can see the compression, but it is not as extreme. The main issue with your image is the color gradients, which are almost impossible in minecraft map generated images. 

Minecraft maps just simply don't have enough color depth for complex images. I was frustrated by it at first as well, but being it is a design element off the game, I do not think there is any way of changing it, unless you push for Mojang to make changes, which will never happen :/ .

**Comment by LosTigeros** [comment]
Gradient tbh works almost perfectly (at least in my logo).
Yeah making images that'll fill perfectly into the game is a little hard.

And about that compression. I wonder why there is no visible compression on Inventivetalent nyan cat video. That still confuse me.

**Comment by Adam759** [comment]
I put the nyancat gif into an animated frames image as well, and it looked fantastic. I think it has to do with the nyan cat just being so simplistic in its colors that it averaged the colors just right.

**Comment by LosTigeros** [comment]
Yes but on my video as you can see this animation looks worse than on original video
