### ISSUE TITLE
Server load increases with the plugin installed

### ISSUE THREAD

**Issue by Maxi22700** [InventivetalentDev/AnimatedFrames#7]
## What steps will reproduce the problem?  
1. Install the plugin
2. Run the server
3. Create a frame, animated or not

**Comment by InventivetalentDev** [comment]
Try editing some of both MapManager's and AnimatedFrames' config options. (MapManager: checkDuplicates, cacheData, sender.delay, sender.amount)  
I went through a lot of versions optimizing the performance of this plugin and it's currently at a point where it performs reasonable without breaking stuff. Due to the animation, it has to cache every single frame of every single section of the frame which (obviously) isn't too resource friendly.  

(You are also the first one to complain about performance since 20+ updates)

**Comment by InventivetalentDev** [comment]
In case this is something major for just your server, please post your server's timings.

**Comment by Maxi22700** [comment]
Thank's for your awnser. I'll see config to try to reduce these problems. It's really strange, because I didn't had these problems with others plugins.

**Comment by Maxi22700** [comment]
Here is the load since our discussion : http://prntscr.com/bj3q41

Do you want I to paste MapManager and AF configs here ?

**Comment by Maxi22700** [comment]
**Animated Frames :** 
# Make sure all animations are started at the same time on startup (useful if you usethe same image on multiple frames)
synchronizedStart: false

# This is a (slightly hacky) fix for images which Java interpretes as the wrong image type
# You should enable this if you get this error when creating a image: http://paste.inventivetalent.org/nokomiquri
fixImageTypes: false


message:
  command:
    create:
      setup:
        first: "&ePlease right-click the &abottom-left corner &eof the frame"
        second: "&ePlease right-click the &atop-right corner &eof the frame"
        set:
          first: "&aFirst corner set"
          second: "&aSecond corner set"
        complete: "&aSetup complete! &eCreating frame '%s' with image '%s'..."
        loading: "&7Loading image & generating maps..."
        starting: "&7Starting playback..."
        started: "&aAnimation started!"
      error:
        exists: "&cFrame already exists"
        invalidImage: "&cInvalid image path specified"
        unknownType: "&cCould not identify the image type. Please make sure you are using the correct link. (Generating anyway, check console for errors)"
    delete:
      stopping: "&eStopping animation..."
      removed: "&aFrame removed."
      error:
        notFound: "&cFrame not found"

**MapManager :**

# If vanilla maps should be allowed to be sent to the players (less efficient, since we need to check the id of every sent map)
allowVanilla: false

# If the plugin checks for duplicate images before creating a new one (Less efficient when first creating a image, but more efficient overall)
checkDuplicates: true

# Cache the packet data in the image object (less CPU intensive for a lot of players, but probably a bit more memory intensive depending on the image size)
cacheData: true

sender:
  # Delay between map packets (ticks)
  delay: 2

  # Maximum amount of map packets sent at once
  amount: 10

  # Allow immediate sending of map data
  allowQueueBypass: true

# Enable this if you are using PaperSpigot (and/or you get this error: http://paste.inventivetalent.org/damuhonebu)
paperSpigot: false

**Comment by InventivetalentDev** [comment]
Looks like a similar performance I usually get. As I said, the plugin can be quite resource intensive, but it also used to be way worse and even crashed some servers completely.

**Comment by Maxi22700** [comment]
Do you've got any ideas to make it less resourceful in a future update ?

**Comment by InventivetalentDev** [comment]
I do. But that would involve completely re-writing both MapManager and AnimatedFrames, and that's currently something I'm not going to do any time soon, since I already did that for AnimatedFrames recently.
