### ISSUE TITLE
AnimatedFrames Custom update?

### ISSUE THREAD

**Issue by Tommetjuhhhh** [InventivetalentDev/AnimatedFrames#70]
Dear Developer,

I have been using AnimatedFrame's for my server for a long time. But we are constantly running against a problem. It's like that, we want to hang up in the server 2 video screens. These screens must be triggered on a command. It is intended that a screen can play a total of 7 images. And then turn completely to standby mode, a black screen. We have several developers looking at this. But we are at the end of the board... Maybe you have a possibility?

We use Minecraft version 1.12.2, Bungeecord and the necessary plug-ins. I hope so that you can help me.

Greetings,

Tom

**Comment by InventivetalentDev** [comment]
I've added the `/afcontent` command to switch the images on frames in one of the recent updates. That might be something that could help you :)
