### ISSUE TITLE
Question (API)

### ISSUE THREAD

**Issue by S3nS3IW00** [InventivetalentDev/AnimatedFrames#72]
Hello!

Can you help me with api? I don't found api node, and I need to setup frames from my plugin.

Thanks!

**Comment by InventivetalentDev** [comment]
Most of the API from this plugin was moved to [MapManager ](https://github.com/InventivetalentDev/MapManager)a while ago, might wanna check that out.  
If you're looking for API stuff directly related to AnimatedFrames, there are only [these events](https://github.com/InventivetalentDev/AnimatedFrames/tree/master/src/main/java/org/inventivetalent/animatedframes/event) you can listen for.
