### ISSUE TITLE
Some issues with the AnimatedFrames

### ISSUE THREAD

**Issue by MJGamingHDTV** [InventivetalentDev/AnimatedFrames#73]
## What steps will reproduce the problem?  
1. Just install the 3 Plugins that are needed and create some images (not animated) 

## What were you expecting to happen? What happened instead?  
I hoped that the Images would be created correctly, but somtimes an images is on the place of another image or the player is see diffrent images.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;* 
AnimatedFerames -> 4.6.9-SNAPSHOT
MapManager -> 1.4.1-SNAPSHOT
PacketListenerAPI -> 3.7.0-SNAPSHOT

## What Spigot version are you using? *Type /version*  
1.8.8_R0.1-SNAPSHOT

## What plugins are you using? *Type /plugins*  
Tested it without any other plugins only with AF, MM and PacketLAPI

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log* 
No... 

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Yes i am using BungeeCord...

**Comment by InventivetalentDev** [comment]
This should be fixed in 4.9.1
