### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BenRulez** [InventivetalentDev/AnimatedFrames#75]
It gives me this error about 10 times after i try and create a frame
http://prntscr.com/knxqyx
Im on 1.12.2 using the 1.12 version of the plugin and the dependancies.

Using Bukkit

**Comment by InventivetalentDev** [comment]
Please use Spigot. This plugin doesn't support bukkit.

**Comment by BenRulez** [comment]
I meant to say using spigot, (actually ment to say not using bukkit) I'm using spigot 1.12.2
