### ISSUE TITLE
Gif playback way to fast

### ISSUE THREAD

**Issue by eliteSchwein** [InventivetalentDev/AnimatedFrames#79]
## What steps will reproduce the problem?  
1. use a normal Gifanimation

## What were you expecting to happen? What happened instead?  
normal Animation Speed, it is slower if you have higher fps (120 is nearly so fast as it should be, and 5fps is so fast that you thing you have taken LSD)

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
AnimatedFrames version 4.7.0-SNAPSHOT

## What Spigot version are you using? *Type /version*  
This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

## What plugins are you using? *Type /plugins*  
Plugins (18): TopLite, LuckPerms, WorldEdit, VoxelSniper, PacketListenerApi, PRcore, ViaVersion, HeadDatabase, AntiLaby, SearchSchematic, MapManager, PRparty, Porty-Bukkit, ZPRcore-Addon, WorldGuard, PRlobbyV2, AnimatedFrames, RegionTeleport

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
nope
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
nope
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
yes, the last Version i used(4.6) was the same Problem......

**Comment by InventivetalentDev** [comment]
Did you try different GIFs? The plugin only takes the delays stored in the gif and plays it, so it might just be the image causing the issue.  Also, would you mind posting the image you used?

**Comment by eliteSchwein** [comment]
Jep all the same Problem, the normal speed is if the gif has 120fps... And my trailer wont load (300mb xD)

**Comment by InventivetalentDev** [comment]
Please give the latest versions a try, I added a default delay to GIFs without delay animation.
