### ISSUE TITLE
[Suggestion] New features with could be added.

### ISSUE THREAD

**Issue by max-legall** [InventivetalentDev/AnimatedFrames#8]
I recently updated my server to 1.9.2, and a plugin we used a lot since years is Pixelator,
Now, it doesn't longer work with 1.9 and it's really sad. In fact, this plugin allowed to obtain maps directly in inventory and place them manually in item frames. That was useful for a same frame placed many times in the server... 

Also, even if you said you were working on that, it should be really cool to place two pictures in the same block like maps could be.

Thank's for your attention

**Comment by InventivetalentDev** [comment]
Sorry, but the first suggestion is not possible. The maps AnimatedFrames generates are only visible for players. So even if the map item in your inventory looked like the correct image, it's just visible like that for you; the server still thinks you're holding a vanilla terrain-map.  
If you need to place images multiple times, just run the same create-command again. The plugin will load the already downloaded image and, if MapManager's 'checkDuplicates' is enabled, it will use exactly the same maps.
(If I ever post another large update for AnimatedFrames, I'll take this feature in consideration and try to implement it)

The second one is already supported, so you should be fine on that :)
