### ISSUE TITLE
Error java.lang.NullPointerExection

### ISSUE THREAD

**Issue by taratata6923** [InventivetalentDev/AnimatedFrames#84]
Hello i can't remove an Image after create
## What steps will reproduce the problem?  
1. /afc test <link>
2. /afrem test
3. Gif not removed

## What were you expecting to happen? What happened instead?  
 Error in console and the Gif don't move (i can resume it)

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
AnimatedFrames_v4.7.0-SNAPSHOT

## What Spigot version are you using? *Type /version*  
i have try with : 
- git-Spigot-f6a273b-1cf8b5d (MC:1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
- git-Spigot-f6a273b-02518f9 (MC:1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
## What plugins are you using? *Type /plugins*  
- AnimatedFrames_v4.7.0-SNAPSHOT
- MapManager_v1.5.1-SNAPSHOT
- PacketListenerAPI_v3.7.1-SNAPSHOT
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/wQphB5gs
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No crash.
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
i just use spigot.

**Comment by InventivetalentDev** [comment]
Just published a new version of MapManager, please try that.

**Comment by taratata6923** [comment]
Hello, the new version of MapManager work perfectly. Thank you very much
