### ISSUE TITLE
NPE on startup

### ISSUE THREAD

**Issue by smmmadden** [InventivetalentDev/AnimatedFrames#87]
Just when I thought it was working fine a restart throws an exception for "Animation length for TmTmc is zero.  Creating non-animated image which is fine and correct.  Immediately following, a warning NPE in AnimatedFrame.scaleImage(AnimatedFrame.java:251). 

Paper 1.13.1 (build 382)
Waterfall b231
AnimatedFrames 4.7.0-snapshot
MapManager 1.5.2-snapshot
Plugins (62): AlchemicalArrows, AnimatedFrames*, Arconix*, AutoBroadcasterPlus*, AutoTorch, BountifulAPI, BungeeServerSigns*, BungeeTabListPlus*, CMIPortals, ColorCodes*, CommandSync*, CorpseReborn*, CreativeGates*, CreeperHeal*, DeluxeMenus*, DoorCloser, dynmap*, EditableSign, EnchantableBlocks, Essentials*, EssentialsAntiBuild*, EssentialsChat*, EssentialsExtras*, EssentialsGeoIP*, EssentialsProtect*, EssentialsSpawn*, HeadDatabase*, HorseTpWithMe, Jobs, Kotlin4MC*, LibsDisguises, Links*, LuckPerms*, LWC, MapManager*, MassiveBooks*, MassiveCore*, Missing_Recipes, NoStrip, OpenInv*, PacketListenerApi*, Parkour, ParkourTopTen, PlaceholderAPI, ProtocolLib*, PulseHealth*, QuickShop, Realistic-Swimming, Residence, Ridables, SaneEconomy*, Seashells, SecurityVillagers, SelectionVisualizer, Sockets4MC*, TintHealth*, Vault*, Votifier, VotingPlugin, WorldBorder, WorldEdit, WorldSystem 
![image](https://user-images.githubusercontent.com/10309346/47332414-33854d00-d64d-11e8-8620-dddea97e267c.png)

**Comment by InventivetalentDev** [comment]
Could you maybe post the image you tried to use?

**Comment by smmmadden** [comment]
this exception is no longer present in the build of yesterday 11/10/2018
