### ISSUE TITLE
AF stops working after some hour

### ISSUE THREAD

**Issue by Duartteno** [InventivetalentDev/AnimatedFrames#91]
## What were you expecting to happen? What happened instead?  
Everything works very well, after a few hours of starting the server, the frames stop showing the picture. Tried with recreate, change size, change picture, change world. Only restart helps.
<img width="615" alt="hm1" src="https://user-images.githubusercontent.com/44345095/48663329-e4d1a400-ea8e-11e8-9616-025231b80bed.png">

It's kinda weird because there are maps, they differ from empty frames.
<img width="1083" alt="hm2" src="https://user-images.githubusercontent.com/44345095/48663333-f7e47400-ea8e-11e8-9ac8-39362caff4fb.png">

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
AnimatedFrames 4.10.0-SNAPSHOT

## What Spigot version are you using? *Type /version*  
git-Paper-1587

## What plugins are you using? *Type /plugins*  
AnimatedFrames, AuthMe, BungeeAddon, ChangeSkin, Citizens, ConditionalCommands, FastAsyncWorldEdit, HolographicDisplays, LibsDisguises, LuckPerms, MapManager, MiniaturePets, NametagEdit, NoCheatPlus, PacketListenerApi, PlaceholderAPI, ProtocolLib, SaneEconomy, SuperVanish, Vault, ViaBackwards, ViaVersion, WorldEdit, WorldGuard

**Comment by InventivetalentDev** [comment]
have you been using GIFs or stationary images?

**Comment by Duartteno** [comment]
@InventivetalentDev .png
