### ISSUE TITLE
AnimatedFrames doesn't work...

### ISSUE THREAD

**Issue by TheGr00m** [InventivetalentDev/AnimatedFrames#94]
## What steps will reproduce the problem?  
1. I want to create a new animated image. so type /afcreate Test https://media2.giphy.com/media/l3vRaWAPakjiEUQow/source.gif
2. I click on the bottom left and top right frames
3. The message "Setup complete! Creating frame 'Test' with image 'https://media2.giphy.com/media/l3vRaWAPakjiEUQow/source.gif'..." appears
4. The message "Loading image & generating maps..." appears
5. That's it.

## What were you expecting to happen? What happened instead?  
I was expecting the animation to play before my eyes, but nothing happened.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
AnimatedFrames_v4.11.0-SNAPSHOT

## What Spigot version are you using? *Type /version*  
Spigot 1.13.2

## What plugins are you using? *Type /plugins*  
worldedit-bukkit-7.0.0-beta-04
PacketListenerAPI_v3.7.1-SNAPSHOT
MapManager_v1.7.0-SNAPSHOT
AnimatedFrames_v4.11.0-SNAPSHOT

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/WsZBrcYB

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
Nope

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Running on local server
Tried to download the GIF and put the file path from my own computer (e.g. C:\\Users\\Me\\myImage.gif), got the same error

**Comment by InventivetalentDev** [comment]
Replace the "media" prefix in the giphy url with an "i".

**Comment by TheGr00m** [comment]
> Replace the "media" prefix in the giphy url with an "i".

Thanks for your quick answer, but it doen't work though... I tried with other GIFs from other URLs too and it's the same problem each time...

**Comment by TheGr00m** [comment]
Thank you! :)
