### ISSUE TITLE
Map data cannot be displayed

### ISSUE THREAD

**Issue by shuiqing2046** [InventivetalentDev/AnimatedFrames#96]
## What steps will reproduce the problem?  
1. Buried treasure map data cannot be displayed.
2. Map data cannot be displayed

**Remove AnimatedFrames error resolution.**

image:
https://i.loli.net/2019/01/06/5c31c56c98752.png

## What Spigot version are you using? *Type /version*  
paper-1.13.2 (493)
## What plugins are you using? *Type /plugins*  
AnimatedFrames_v4.11.1-SNAPSHOT.jar
MapManager_v1.7.0-SNAPSHOT.jar
PacketListenerAPI_v3.7.1-SNAPSHOT.jar
## Do you have an error log? Use [pastebin.com](http://pastebin.com).   
No error log

**Comment by InventivetalentDev** [comment]
You can download the latest version of MapManager and set the `forcedOffset` config option to a number greater than the map IDs your players create to prevent them from being overwritten.

**Comment by shuiqing2046** [comment]
> You can download the latest version of MapManager and set the `forcedOffset` config option to a number greater than the map IDs your players create to prevent them from being overwritten.

I don't know how to operate. Can you elaborate?

**Comment by shuiqing2046** [comment]
> You can download the latest version of MapManager and set the `forcedOffset` config option to a number greater than the map IDs your players create to prevent them from being overwritten.

I don't know how to operate. Can you elaborate?

**Comment by InventivetalentDev** [comment]
* Download the latest MapManager version from https://www.spigotmc.org/resources/api-mapmanager.19198/
* Go to plugins/MapManager and open config.yml
* add a line with `forcedOffset: 20` (or whatever amount you think your players need for maps)
