### ISSUE TITLE
Feature Request: Command to set an existing image to a new set of frames

### ISSUE THREAD

**Issue by TheGr00m** [InventivetalentDev/AnimatedFrames#98]
Hi !

Could it be possible (or is it already) to place an image several times, without having to create it several times?

Like I have an image that I'd like to place on 4 sides of a cube, do I have to create it 4 times with 4 different names, or is there already a command to place it again in a new frame? If there's no such thing, could it be possible to implement it?

Thanks for your amazing plugin and your hard work :)

**Comment by InventivetalentDev** [comment]
You will have to re-create a new frame even if you're using the same image. But the plugin will use a cached version of that image internally.
