### ISSUE TITLE
Feature Request: Select which world gets used for maps

### ISSUE THREAD

**Issue by LadyHaley** [InventivetalentDev/AnimatedFrames#99]
So an issue I'm having right now is that players are making maps, only to have them be taken up by an image, I think it would be great if we could select another world for the Image data to be placed in, weather it be the Nether or another world added by a multiverse plugin. Is that something you could add? I know you can change the offset for when the maps start but I feel like this would be a much better fix for it, also what is the max amount of maps a world can have, I noticed in the config it said not to put it too high but I dont know what too high looks like.

**Comment by InventivetalentDev** [comment]
> select another world for the Image data to be placed in  

The way Minecraft's image data works, this is unfortunately not possible.   
The only way to still properly allow vanilla/player-created maps is to change the offset in the MapManager config. There are about 32k Map IDs available, so if you don't have too many animated frames you can set that number pretty high. Keep in mind though that every individual map and every frame takes up another ID, so e.g. a still image that's placed on an area of 4x5 blocks would already take up 20 IDs and an animation of the same size with 10 gif-frames would use 200 frames and so on.

**Comment by InventivetalentDev** [comment]
The way the plugin works is by pre-loading the GIF's individual frames onto maps and sending it to the players, to allow for a smooth animation. So the map updates are done before the animation is ever played, which is why the plugin uses up a lot of map IDs.
